enum CityTier { tier1, tier2 }

class IndiaCity {
  const IndiaCity({
    required this.id,
    required this.city,
    required this.stateUt,
    required this.tier,
    required this.employmentCluster,
  });

  final int id;
  final String city;
  final String stateUt;
  final CityTier tier;
  final String employmentCluster;
}

/// Sourced from the user-provided city master list (108 cities, Tier 1/
/// Tier 2 India), used for the Job Matches location filter.
const List<IndiaCity> kIndiaCities = [
  IndiaCity(id: 1, city: 'Ahmedabad', stateUt: 'Gujarat', tier: CityTier.tier1, employmentCluster: 'Ahmedabad Metropolitan Region'),
  IndiaCity(id: 2, city: 'Bengaluru', stateUt: 'Karnataka', tier: CityTier.tier1, employmentCluster: 'Bengaluru Metropolitan Region'),
  IndiaCity(id: 3, city: 'Chennai', stateUt: 'Tamil Nadu', tier: CityTier.tier1, employmentCluster: 'Chennai Metropolitan Region'),
  IndiaCity(id: 4, city: 'Delhi', stateUt: 'Delhi', tier: CityTier.tier1, employmentCluster: 'Delhi NCR'),
  IndiaCity(id: 5, city: 'Hyderabad', stateUt: 'Telangana', tier: CityTier.tier1, employmentCluster: 'Hyderabad Metropolitan Region'),
  IndiaCity(id: 6, city: 'Kolkata', stateUt: 'West Bengal', tier: CityTier.tier1, employmentCluster: 'Kolkata Metropolitan Region'),
  IndiaCity(id: 7, city: 'Mumbai', stateUt: 'Maharashtra', tier: CityTier.tier1, employmentCluster: 'Mumbai Metropolitan Region'),
  IndiaCity(id: 8, city: 'Pune', stateUt: 'Maharashtra', tier: CityTier.tier1, employmentCluster: 'Pune Metropolitan Region'),
  IndiaCity(id: 9, city: 'Agra', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Agra Employment Market'),
  IndiaCity(id: 10, city: 'Ajmer', stateUt: 'Rajasthan', tier: CityTier.tier2, employmentCluster: 'Ajmer Employment Market'),
  IndiaCity(id: 11, city: 'Akola', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Akola Employment Market'),
  IndiaCity(id: 12, city: 'Aligarh', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Aligarh Employment Market'),
  IndiaCity(id: 13, city: 'Amravati', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Amravati Employment Market'),
  IndiaCity(id: 14, city: 'Amritsar', stateUt: 'Punjab', tier: CityTier.tier2, employmentCluster: 'Amritsar Employment Market'),
  IndiaCity(id: 15, city: 'Anand', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Anand Employment Market'),
  IndiaCity(id: 16, city: 'Asansol', stateUt: 'West Bengal', tier: CityTier.tier2, employmentCluster: 'Asansol Employment Market'),
  IndiaCity(id: 17, city: 'Aurangabad / Chhatrapati Sambhajinagar', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Aurangabad / Chhatrapati Sambhajinagar Employment Market'),
  IndiaCity(id: 18, city: 'Bareilly', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Bareilly Employment Market'),
  IndiaCity(id: 19, city: 'Bardhaman', stateUt: 'West Bengal', tier: CityTier.tier2, employmentCluster: 'Bardhaman Employment Market'),
  IndiaCity(id: 20, city: 'Belagavi', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Belagavi Employment Market'),
  IndiaCity(id: 21, city: 'Bhavnagar', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Bhavnagar Employment Market'),
  IndiaCity(id: 22, city: 'Bhiwandi', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Mumbai Metropolitan Region'),
  IndiaCity(id: 23, city: 'Bhopal', stateUt: 'Madhya Pradesh', tier: CityTier.tier2, employmentCluster: 'Bhopal Employment Market'),
  IndiaCity(id: 24, city: 'Bhubaneswar', stateUt: 'Odisha', tier: CityTier.tier2, employmentCluster: 'Bhubaneswar Employment Market'),
  IndiaCity(id: 25, city: 'Bikaner', stateUt: 'Rajasthan', tier: CityTier.tier2, employmentCluster: 'Bikaner Employment Market'),
  IndiaCity(id: 26, city: 'Bokaro Steel City', stateUt: 'Jharkhand', tier: CityTier.tier2, employmentCluster: 'Bokaro Steel City Employment Market'),
  IndiaCity(id: 27, city: 'Ballari', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Ballari Employment Market'),
  IndiaCity(id: 28, city: 'Bhilai', stateUt: 'Chhattisgarh', tier: CityTier.tier2, employmentCluster: 'Bhilai Employment Market'),
  IndiaCity(id: 29, city: 'Chandigarh', stateUt: 'Chandigarh', tier: CityTier.tier2, employmentCluster: 'Chandigarh Employment Market'),
  IndiaCity(id: 30, city: 'Coimbatore', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Coimbatore Employment Market'),
  IndiaCity(id: 31, city: 'Cuttack', stateUt: 'Odisha', tier: CityTier.tier2, employmentCluster: 'Cuttack Employment Market'),
  IndiaCity(id: 32, city: 'Dehradun', stateUt: 'Uttarakhand', tier: CityTier.tier2, employmentCluster: 'Dehradun Employment Market'),
  IndiaCity(id: 33, city: 'Dombivli', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Mumbai Metropolitan Region'),
  IndiaCity(id: 34, city: 'Dhanbad', stateUt: 'Jharkhand', tier: CityTier.tier2, employmentCluster: 'Dhanbad Employment Market'),
  IndiaCity(id: 35, city: 'Durgapur', stateUt: 'West Bengal', tier: CityTier.tier2, employmentCluster: 'Durgapur Employment Market'),
  IndiaCity(id: 36, city: 'Erode', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Erode Employment Market'),
  IndiaCity(id: 37, city: 'Faridabad', stateUt: 'Haryana', tier: CityTier.tier2, employmentCluster: 'Delhi NCR'),
  IndiaCity(id: 38, city: 'Ghaziabad', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Delhi NCR'),
  IndiaCity(id: 39, city: 'Gorakhpur', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Gorakhpur Employment Market'),
  IndiaCity(id: 40, city: 'Guntur', stateUt: 'Andhra Pradesh', tier: CityTier.tier2, employmentCluster: 'Guntur Employment Market'),
  IndiaCity(id: 41, city: 'Gurugram', stateUt: 'Haryana', tier: CityTier.tier2, employmentCluster: 'Delhi NCR'),
  IndiaCity(id: 42, city: 'Guwahati', stateUt: 'Assam', tier: CityTier.tier2, employmentCluster: 'Guwahati Employment Market'),
  IndiaCity(id: 43, city: 'Gwalior', stateUt: 'Madhya Pradesh', tier: CityTier.tier2, employmentCluster: 'Gwalior Employment Market'),
  IndiaCity(id: 44, city: 'Hubballi-Dharwad', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Hubballi-Dharwad Employment Market'),
  IndiaCity(id: 45, city: 'Indore', stateUt: 'Madhya Pradesh', tier: CityTier.tier2, employmentCluster: 'Indore Employment Market'),
  IndiaCity(id: 46, city: 'Jabalpur', stateUt: 'Madhya Pradesh', tier: CityTier.tier2, employmentCluster: 'Jabalpur Employment Market'),
  IndiaCity(id: 47, city: 'Jaipur', stateUt: 'Rajasthan', tier: CityTier.tier2, employmentCluster: 'Jaipur Employment Market'),
  IndiaCity(id: 48, city: 'Jalandhar', stateUt: 'Punjab', tier: CityTier.tier2, employmentCluster: 'Jalandhar Employment Market'),
  IndiaCity(id: 49, city: 'Jalgaon', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Jalgaon Employment Market'),
  IndiaCity(id: 50, city: 'Jammu', stateUt: 'Jammu & Kashmir', tier: CityTier.tier2, employmentCluster: 'Jammu Employment Market'),
  IndiaCity(id: 51, city: 'Jamshedpur', stateUt: 'Jharkhand', tier: CityTier.tier2, employmentCluster: 'Jamshedpur Employment Market'),
  IndiaCity(id: 52, city: 'Jamnagar', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Jamnagar Employment Market'),
  IndiaCity(id: 53, city: 'Jhansi', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Jhansi Employment Market'),
  IndiaCity(id: 54, city: 'Jodhpur', stateUt: 'Rajasthan', tier: CityTier.tier2, employmentCluster: 'Jodhpur Employment Market'),
  IndiaCity(id: 55, city: 'Kalaburagi', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Kalaburagi Employment Market'),
  IndiaCity(id: 56, city: 'Kakinada', stateUt: 'Andhra Pradesh', tier: CityTier.tier2, employmentCluster: 'Kakinada Employment Market'),
  IndiaCity(id: 57, city: 'Kannur', stateUt: 'Kerala', tier: CityTier.tier2, employmentCluster: 'Kannur Employment Market'),
  IndiaCity(id: 58, city: 'Kanpur', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Kanpur Employment Market'),
  IndiaCity(id: 59, city: 'Karimnagar', stateUt: 'Telangana', tier: CityTier.tier2, employmentCluster: 'Karimnagar Employment Market'),
  IndiaCity(id: 60, city: 'Karnal', stateUt: 'Haryana', tier: CityTier.tier2, employmentCluster: 'Karnal Employment Market'),
  IndiaCity(id: 61, city: 'Kochi', stateUt: 'Kerala', tier: CityTier.tier2, employmentCluster: 'Kochi Employment Market'),
  IndiaCity(id: 62, city: 'Kolhapur', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Kolhapur Employment Market'),
  IndiaCity(id: 63, city: 'Kollam', stateUt: 'Kerala', tier: CityTier.tier2, employmentCluster: 'Kollam Employment Market'),
  IndiaCity(id: 64, city: 'Kota', stateUt: 'Rajasthan', tier: CityTier.tier2, employmentCluster: 'Kota Employment Market'),
  IndiaCity(id: 65, city: 'Kozhikode', stateUt: 'Kerala', tier: CityTier.tier2, employmentCluster: 'Kozhikode Employment Market'),
  IndiaCity(id: 66, city: 'Kurnool', stateUt: 'Andhra Pradesh', tier: CityTier.tier2, employmentCluster: 'Kurnool Employment Market'),
  IndiaCity(id: 67, city: 'Ludhiana', stateUt: 'Punjab', tier: CityTier.tier2, employmentCluster: 'Ludhiana Employment Market'),
  IndiaCity(id: 68, city: 'Lucknow', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Lucknow Employment Market'),
  IndiaCity(id: 69, city: 'Madurai', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Madurai Employment Market'),
  IndiaCity(id: 70, city: 'Mathura', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Mathura Employment Market'),
  IndiaCity(id: 71, city: 'Mangaluru', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Mangaluru Employment Market'),
  IndiaCity(id: 72, city: 'Meerut', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Meerut Employment Market'),
  IndiaCity(id: 73, city: 'Moradabad', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Moradabad Employment Market'),
  IndiaCity(id: 74, city: 'Mysuru', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Mysuru Employment Market'),
  IndiaCity(id: 75, city: 'Nagpur', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Nagpur Employment Market'),
  IndiaCity(id: 76, city: 'Nanded', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Nanded Employment Market'),
  IndiaCity(id: 77, city: 'Nadiad', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Nadiad Employment Market'),
  IndiaCity(id: 78, city: 'Nashik', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Nashik Employment Market'),
  IndiaCity(id: 79, city: 'Nellore', stateUt: 'Andhra Pradesh', tier: CityTier.tier2, employmentCluster: 'Nellore Employment Market'),
  IndiaCity(id: 80, city: 'Noida', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Delhi NCR'),
  IndiaCity(id: 81, city: 'Patna', stateUt: 'Bihar', tier: CityTier.tier2, employmentCluster: 'Patna Employment Market'),
  IndiaCity(id: 82, city: 'Pimpri-Chinchwad', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Pune Metropolitan Region'),
  IndiaCity(id: 83, city: 'Puducherry', stateUt: 'Puducherry', tier: CityTier.tier2, employmentCluster: 'Puducherry Employment Market'),
  IndiaCity(id: 84, city: 'Prayagraj', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Prayagraj Employment Market'),
  IndiaCity(id: 85, city: 'Raipur', stateUt: 'Chhattisgarh', tier: CityTier.tier2, employmentCluster: 'Raipur Employment Market'),
  IndiaCity(id: 86, city: 'Rajkot', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Rajkot Employment Market'),
  IndiaCity(id: 87, city: 'Ranchi', stateUt: 'Jharkhand', tier: CityTier.tier2, employmentCluster: 'Ranchi Employment Market'),
  IndiaCity(id: 88, city: 'Rourkela', stateUt: 'Odisha', tier: CityTier.tier2, employmentCluster: 'Rourkela Employment Market'),
  IndiaCity(id: 89, city: 'Saharanpur', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Saharanpur Employment Market'),
  IndiaCity(id: 90, city: 'Salem', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Salem Employment Market'),
  IndiaCity(id: 91, city: 'Sangli', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Sangli Employment Market'),
  IndiaCity(id: 92, city: 'Shimla', stateUt: 'Himachal Pradesh', tier: CityTier.tier2, employmentCluster: 'Shimla Employment Market'),
  IndiaCity(id: 93, city: 'Siliguri', stateUt: 'West Bengal', tier: CityTier.tier2, employmentCluster: 'Siliguri Employment Market'),
  IndiaCity(id: 94, city: 'Solapur', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Solapur Employment Market'),
  IndiaCity(id: 95, city: 'Srinagar', stateUt: 'Jammu & Kashmir', tier: CityTier.tier2, employmentCluster: 'Srinagar Employment Market'),
  IndiaCity(id: 96, city: 'Surat', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Surat Employment Market'),
  IndiaCity(id: 97, city: 'Thanjavur', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Thanjavur Employment Market'),
  IndiaCity(id: 98, city: 'Thiruvananthapuram', stateUt: 'Kerala', tier: CityTier.tier2, employmentCluster: 'Thiruvananthapuram Employment Market'),
  IndiaCity(id: 99, city: 'Thrissur', stateUt: 'Kerala', tier: CityTier.tier2, employmentCluster: 'Thrissur Employment Market'),
  IndiaCity(id: 100, city: 'Tiruchirappalli', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Tiruchirappalli Employment Market'),
  IndiaCity(id: 101, city: 'Tirunelveli', stateUt: 'Tamil Nadu', tier: CityTier.tier2, employmentCluster: 'Tirunelveli Employment Market'),
  IndiaCity(id: 102, city: 'Ujjain', stateUt: 'Madhya Pradesh', tier: CityTier.tier2, employmentCluster: 'Ujjain Employment Market'),
  IndiaCity(id: 103, city: 'Vijayapura', stateUt: 'Karnataka', tier: CityTier.tier2, employmentCluster: 'Vijayapura Employment Market'),
  IndiaCity(id: 104, city: 'Vadodara', stateUt: 'Gujarat', tier: CityTier.tier2, employmentCluster: 'Vadodara Employment Market'),
  IndiaCity(id: 105, city: 'Varanasi', stateUt: 'Uttar Pradesh', tier: CityTier.tier2, employmentCluster: 'Varanasi Employment Market'),
  IndiaCity(id: 106, city: 'Vasai-Virar', stateUt: 'Maharashtra', tier: CityTier.tier2, employmentCluster: 'Mumbai Metropolitan Region'),
  IndiaCity(id: 107, city: 'Vijayawada', stateUt: 'Andhra Pradesh', tier: CityTier.tier2, employmentCluster: 'Vijayawada Employment Market'),
  IndiaCity(id: 108, city: 'Visakhapatnam', stateUt: 'Andhra Pradesh', tier: CityTier.tier2, employmentCluster: 'Visakhapatnam Employment Market'),
];
