class TopCompany {
  const TopCompany({
    required this.rank,
    required this.name,
    required this.industry,
  });

  final int rank;
  final String name;
  final String industry;
}

/// Sourced from the user-provided Top 250 India companies list, used to
/// badge job matches from major employers.
const List<TopCompany> kTopCompanies = [
  TopCompany(rank: 1, name: 'Tata Consultancy Services (TCS)', industry: 'IT Services'),
  TopCompany(rank: 2, name: 'Infosys', industry: 'IT Services'),
  TopCompany(rank: 3, name: 'Wipro', industry: 'IT Services'),
  TopCompany(rank: 4, name: 'HCLTech', industry: 'IT Services'),
  TopCompany(rank: 5, name: 'Tech Mahindra', industry: 'IT Services'),
  TopCompany(rank: 6, name: 'LTIMindtree', industry: 'IT Services'),
  TopCompany(rank: 7, name: 'Mphasis', industry: 'IT Services'),
  TopCompany(rank: 8, name: 'Persistent Systems', industry: 'IT Services'),
  TopCompany(rank: 9, name: 'Coforge', industry: 'IT Services'),
  TopCompany(rank: 10, name: 'L&T Technology Services', industry: 'IT Services'),
  TopCompany(rank: 11, name: 'Larsen & Toubro', industry: 'IT Services'),
  TopCompany(rank: 12, name: 'Cyient', industry: 'IT Services'),
  TopCompany(rank: 13, name: 'KPIT Technologies', industry: 'IT Services'),
  TopCompany(rank: 14, name: 'Zensar Technologies', industry: 'IT Services'),
  TopCompany(rank: 15, name: 'Hexaware Technologies', industry: 'IT Services'),
  TopCompany(rank: 16, name: 'Mastek', industry: 'IT Services'),
  TopCompany(rank: 17, name: 'Birlasoft', industry: 'IT Services'),
  TopCompany(rank: 18, name: 'Tata Elxsi', industry: 'IT Services'),
  TopCompany(rank: 19, name: 'Sonata Software', industry: 'IT Services'),
  TopCompany(rank: 20, name: 'Oracle India', industry: 'IT / Software'),
  TopCompany(rank: 21, name: 'IBM India', industry: 'IT / Software'),
  TopCompany(rank: 22, name: 'Accenture India', industry: 'IT Services'),
  TopCompany(rank: 23, name: 'Cognizant India', industry: 'IT Services'),
  TopCompany(rank: 24, name: 'Capgemini India', industry: 'IT Services'),
  TopCompany(rank: 25, name: 'DXC Technology India', industry: 'IT Services'),
  TopCompany(rank: 26, name: 'NTT DATA India', industry: 'IT Services'),
  TopCompany(rank: 27, name: 'Genpact', industry: 'IT / BPM'),
  TopCompany(rank: 28, name: 'Concentrix', industry: 'IT / BPM'),
  TopCompany(rank: 29, name: 'Teleperformance India', industry: 'IT / BPM'),
  TopCompany(rank: 30, name: 'WNS Global Services', industry: 'IT / BPM'),
  TopCompany(rank: 31, name: 'Sutherland Global Services', industry: 'IT / BPM'),
  TopCompany(rank: 32, name: 'Foundever India', industry: 'IT / BPM'),
  TopCompany(rank: 33, name: 'EXL Service', industry: 'IT / BPM'),
  TopCompany(rank: 34, name: 'Evalueserve', industry: 'IT / BPM'),
  TopCompany(rank: 35, name: 'TTEC India', industry: 'IT / BPM'),
  TopCompany(rank: 36, name: 'State Bank of India (SBI)', industry: 'Banking'),
  TopCompany(rank: 37, name: 'HDFC Bank', industry: 'Banking'),
  TopCompany(rank: 38, name: 'ICICI Bank', industry: 'Banking'),
  TopCompany(rank: 39, name: 'Axis Bank', industry: 'Banking'),
  TopCompany(rank: 40, name: 'Kotak Mahindra Bank', industry: 'Banking'),
  TopCompany(rank: 41, name: 'IndusInd Bank', industry: 'Banking'),
  TopCompany(rank: 42, name: 'Yes Bank', industry: 'Banking'),
  TopCompany(rank: 43, name: 'IDFC FIRST Bank', industry: 'Banking'),
  TopCompany(rank: 44, name: 'Federal Bank', industry: 'Banking'),
  TopCompany(rank: 45, name: 'Bank of Baroda', industry: 'Banking'),
  TopCompany(rank: 46, name: 'Canara Bank', industry: 'Banking'),
  TopCompany(rank: 47, name: 'Punjab National Bank', industry: 'Banking'),
  TopCompany(rank: 48, name: 'Union Bank of India', industry: 'Banking'),
  TopCompany(rank: 49, name: 'Bank of India', industry: 'Banking'),
  TopCompany(rank: 50, name: 'Indian Bank', industry: 'Banking'),
  TopCompany(rank: 51, name: 'Indian Overseas Bank', industry: 'Banking'),
  TopCompany(rank: 52, name: 'UCO Bank', industry: 'Banking'),
  TopCompany(rank: 53, name: 'Central Bank of India', industry: 'Banking'),
  TopCompany(rank: 54, name: 'Bank of Maharashtra', industry: 'Banking'),
  TopCompany(rank: 55, name: 'South Indian Bank', industry: 'Banking'),
  TopCompany(rank: 56, name: 'RBL Bank', industry: 'Banking'),
  TopCompany(rank: 57, name: 'AU Small Finance Bank', industry: 'Banking'),
  TopCompany(rank: 58, name: 'Ujjivan Small Finance Bank', industry: 'Banking'),
  TopCompany(rank: 59, name: 'Bajaj Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 60, name: 'Bajaj Finserv', industry: 'Financial Services'),
  TopCompany(rank: 61, name: 'Aditya Birla Capital', industry: 'Financial Services'),
  TopCompany(rank: 62, name: 'Tata Capital', industry: 'Financial Services'),
  TopCompany(rank: 63, name: 'Shriram Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 64, name: 'Mahindra Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 65, name: 'Cholamandalam Investment & Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 66, name: 'Muthoot Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 67, name: 'Manappuram Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 68, name: 'L&T Finance', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 69, name: 'HDB Financial Services', industry: 'NBFC / Financial Services'),
  TopCompany(rank: 70, name: 'SBI Life Insurance', industry: 'Insurance'),
  TopCompany(rank: 71, name: 'LIC of India', industry: 'Insurance'),
  TopCompany(rank: 72, name: 'HDFC Life', industry: 'Insurance'),
  TopCompany(rank: 73, name: 'ICICI Prudential Life Insurance', industry: 'Insurance'),
  TopCompany(rank: 74, name: 'Max Life Insurance', industry: 'Insurance'),
  TopCompany(rank: 75, name: 'Bajaj Allianz Life Insurance', industry: 'Insurance'),
  TopCompany(rank: 76, name: 'Tata AIA Life Insurance', industry: 'Insurance'),
  TopCompany(rank: 77, name: 'Aditya Birla Sun Life Insurance', industry: 'Insurance'),
  TopCompany(rank: 78, name: 'Star Health and Allied Insurance', industry: 'Insurance'),
  TopCompany(rank: 79, name: 'New India Assurance', industry: 'Insurance'),
  TopCompany(rank: 80, name: 'Reliance Industries', industry: 'Diversified / Energy'),
  TopCompany(rank: 81, name: 'Adani Enterprises', industry: 'Diversified / Infrastructure'),
  TopCompany(rank: 82, name: 'Adani Ports and SEZ', industry: 'Infrastructure'),
  TopCompany(rank: 83, name: 'Adani Power', industry: 'Power'),
  TopCompany(rank: 84, name: 'Adani Green Energy', industry: 'Renewable Energy'),
  TopCompany(rank: 85, name: 'Larsen & Toubro (L&T)', industry: 'Engineering / Infrastructure'),
  TopCompany(rank: 86, name: 'Tata Consumer Products', industry: 'Conglomerate'),
  TopCompany(rank: 87, name: 'Mahindra & Mahindra', industry: 'Automotive / Diversified'),
  TopCompany(rank: 88, name: 'Bajaj Holdings & Investment', industry: 'Conglomerate'),
  TopCompany(rank: 89, name: 'Aditya Birla Management Corporation', industry: 'Conglomerate'),
  TopCompany(rank: 90, name: 'Godrej Industries', industry: 'Conglomerate'),
  TopCompany(rank: 91, name: 'Vedanta', industry: 'Metals / Mining'),
  TopCompany(rank: 92, name: 'JSW Group', industry: 'Conglomerate / Infrastructure'),
  TopCompany(rank: 93, name: 'Jindal Steel & Power', industry: 'Steel / Energy'),
  TopCompany(rank: 94, name: 'Essar Oil', industry: 'Conglomerate'),
  TopCompany(rank: 95, name: 'Indian Oil Corporation (IOCL)', industry: 'Oil & Gas'),
  TopCompany(rank: 96, name: 'Bharat Petroleum (BPCL)', industry: 'Oil & Gas'),
  TopCompany(rank: 97, name: 'Hindustan Petroleum (HPCL)', industry: 'Oil & Gas'),
  TopCompany(rank: 98, name: 'Oil and Natural Gas Corporation (ONGC)', industry: 'Oil & Gas'),
  TopCompany(rank: 99, name: 'GAIL India', industry: 'Oil & Gas'),
  TopCompany(rank: 100, name: 'Petronet LNG', industry: 'Oil & Gas'),
  TopCompany(rank: 101, name: 'Nayara Energy', industry: 'Oil & Gas'),
  TopCompany(rank: 102, name: 'Jio-bp', industry: 'Oil & Gas / Retail'),
  TopCompany(rank: 103, name: 'NTPC', industry: 'Power'),
  TopCompany(rank: 104, name: 'Power Grid Corporation of India', industry: 'Power'),
  TopCompany(rank: 105, name: 'NHPC', industry: 'Power'),
  TopCompany(rank: 106, name: 'SJVN', industry: 'Power'),
  TopCompany(rank: 107, name: 'REC Limited', industry: 'Power / Finance'),
  TopCompany(rank: 108, name: 'Power Finance Corporation (PFC)', industry: 'Power / Finance'),
  TopCompany(rank: 109, name: 'Tata Power', industry: 'Power'),
  TopCompany(rank: 110, name: 'JSW Energy', industry: 'Power'),
  TopCompany(rank: 111, name: 'Torrent Power', industry: 'Power'),
  TopCompany(rank: 112, name: 'Adani Energy Solutions', industry: 'Power'),
  TopCompany(rank: 113, name: 'CESC', industry: 'Power'),
  TopCompany(rank: 114, name: 'Tata Motors', industry: 'Automotive'),
  TopCompany(rank: 115, name: 'Maruti Suzuki India', industry: 'Automotive'),
  TopCompany(rank: 116, name: 'Hyundai Motor India', industry: 'Automotive'),
  TopCompany(rank: 117, name: 'Toyota Kirloskar Motor', industry: 'Automotive'),
  TopCompany(rank: 118, name: 'Honda Cars India', industry: 'Automotive'),
  TopCompany(rank: 119, name: 'Kia India', industry: 'Automotive'),
  TopCompany(rank: 120, name: 'Ashok Leyland', industry: 'Automotive'),
  TopCompany(rank: 121, name: 'Eicher Motors', industry: 'Automotive'),
  TopCompany(rank: 122, name: 'TVS Motor Company', industry: 'Automotive'),
  TopCompany(rank: 123, name: 'Bajaj Auto', industry: 'Automotive'),
  TopCompany(rank: 124, name: 'Hero MotoCorp', industry: 'Automotive'),
  TopCompany(rank: 125, name: 'Force Motors', industry: 'Automotive'),
  TopCompany(rank: 126, name: 'Tata AutoComp Systems', industry: 'Auto Components'),
  TopCompany(rank: 127, name: 'Motherson', industry: 'Auto Components'),
  TopCompany(rank: 128, name: 'Bosch India', industry: 'Auto Components'),
  TopCompany(rank: 129, name: 'ZF India', industry: 'Auto Components'),
  TopCompany(rank: 130, name: 'Continental India', industry: 'Auto Components'),
  TopCompany(rank: 131, name: 'Schaeffler India', industry: 'Auto Components'),
  TopCompany(rank: 132, name: 'Cummins India', industry: 'Engineering'),
  TopCompany(rank: 133, name: 'Siemens India', industry: 'Engineering'),
  TopCompany(rank: 134, name: 'ABB India', industry: 'Engineering'),
  TopCompany(rank: 135, name: 'Honeywell India', industry: 'Engineering / Technology'),
  TopCompany(rank: 136, name: 'Schneider Electric India', industry: 'Engineering / Energy'),
  TopCompany(rank: 137, name: 'GE Vernova India', industry: 'Energy Technology'),
  TopCompany(rank: 138, name: 'Bharat Heavy Electricals (BHEL)', industry: 'Engineering / PSU'),
  TopCompany(rank: 139, name: 'HAL', industry: 'Aerospace / Defence'),
  TopCompany(rank: 140, name: 'Bharat Electronics (BEL)', industry: 'Defence Electronics'),
  TopCompany(rank: 141, name: 'Bharat Dynamics (BDL)', industry: 'Defence'),
  TopCompany(rank: 142, name: 'Mazagon Dock Shipbuilders', industry: 'Shipbuilding / Defence'),
  TopCompany(rank: 143, name: 'Cochin Shipyard', industry: 'Shipbuilding / Defence'),
  TopCompany(rank: 144, name: 'Garden Reach Shipbuilders', industry: 'Shipbuilding / Defence'),
  TopCompany(rank: 145, name: 'Tata Steel', industry: 'Steel'),
  TopCompany(rank: 146, name: 'JSW Steel', industry: 'Steel'),
  TopCompany(rank: 147, name: 'SAIL', industry: 'Steel / PSU'),
  TopCompany(rank: 148, name: 'Hindalco Industries', industry: 'Metals'),
  TopCompany(rank: 149, name: 'Vedanta Aluminium', industry: 'Metals'),
  TopCompany(rank: 150, name: 'Jindal Stainless', industry: 'Steel'),
  TopCompany(rank: 151, name: 'UltraTech Cement', industry: 'Cement'),
  TopCompany(rank: 152, name: 'ACC Limited', industry: 'Cement'),
  TopCompany(rank: 153, name: 'Ambuja Cements', industry: 'Cement'),
  TopCompany(rank: 154, name: 'Shree Cement', industry: 'Cement'),
  TopCompany(rank: 155, name: 'Dalmia Bharat', industry: 'Cement'),
  TopCompany(rank: 156, name: 'Grasim Industries', industry: 'Diversified / Cement'),
  TopCompany(rank: 157, name: 'Pidilite Industries', industry: 'Chemicals'),
  TopCompany(rank: 158, name: 'Asian Paints', industry: 'Paints / Chemicals'),
  TopCompany(rank: 159, name: 'Berger Paints', industry: 'Paints / Chemicals'),
  TopCompany(rank: 160, name: 'UPL', industry: 'Agrochemicals'),
  TopCompany(rank: 161, name: 'Deepak Fertilisers', industry: 'Chemicals / Fertilisers'),
  TopCompany(rank: 162, name: 'Tata Chemicals', industry: 'Chemicals'),
  TopCompany(rank: 163, name: 'Aarti Industries', industry: 'Chemicals'),
  TopCompany(rank: 164, name: 'SRF Limited', industry: 'Chemicals'),
  TopCompany(rank: 165, name: 'Hindustan Unilever (HUL)', industry: 'FMCG'),
  TopCompany(rank: 166, name: 'ITC', industry: 'FMCG / Diversified'),
  TopCompany(rank: 167, name: 'Nestlé India', industry: 'FMCG'),
  TopCompany(rank: 168, name: 'Britannia Industries', industry: 'FMCG'),
  TopCompany(rank: 169, name: 'Dabur India', industry: 'FMCG'),
  TopCompany(rank: 170, name: 'Marico', industry: 'FMCG'),
  TopCompany(rank: 171, name: 'Godrej Consumer Products', industry: 'FMCG'),
  TopCompany(rank: 172, name: 'Procter & Gamble India', industry: 'FMCG'),
  TopCompany(rank: 173, name: 'Colgate-Palmolive India', industry: 'FMCG'),
  TopCompany(rank: 174, name: 'Reckitt India', industry: 'FMCG'),
  TopCompany(rank: 175, name: 'Emami', industry: 'FMCG'),
  TopCompany(rank: 176, name: 'Jyothy Labs', industry: 'FMCG'),
  TopCompany(rank: 177, name: 'Varun Beverages', industry: 'FMCG'),
  TopCompany(rank: 178, name: 'United Breweries', industry: 'FMCG / Beverages'),
  TopCompany(rank: 179, name: 'Sun Pharmaceutical Industries', industry: 'Pharmaceuticals'),
  TopCompany(rank: 180, name: 'Dr. Reddy\'s Laboratories', industry: 'Pharmaceuticals'),
  TopCompany(rank: 181, name: 'Cipla', industry: 'Pharmaceuticals'),
  TopCompany(rank: 182, name: 'Lupin', industry: 'Pharmaceuticals'),
  TopCompany(rank: 183, name: 'Aurobindo Pharma', industry: 'Pharmaceuticals'),
  TopCompany(rank: 184, name: 'Zydus Lifesciences', industry: 'Pharmaceuticals'),
  TopCompany(rank: 185, name: 'Torrent Pharmaceuticals', industry: 'Pharmaceuticals'),
  TopCompany(rank: 186, name: 'Mankind Pharma', industry: 'Pharmaceuticals'),
  TopCompany(rank: 187, name: 'Alkem Laboratories', industry: 'Pharmaceuticals'),
  TopCompany(rank: 188, name: 'Glenmark Pharmaceuticals', industry: 'Pharmaceuticals'),
  TopCompany(rank: 189, name: 'Abbott India', industry: 'Pharmaceuticals'),
  TopCompany(rank: 190, name: 'Biocon', industry: 'Biopharma'),
  TopCompany(rank: 191, name: 'Divi\'s Laboratories', industry: 'Pharmaceuticals'),
  TopCompany(rank: 192, name: 'Apollo Hospitals', industry: 'Healthcare'),
  TopCompany(rank: 193, name: 'Fortis Healthcare', industry: 'Healthcare'),
  TopCompany(rank: 194, name: 'Max Healthcare', industry: 'Healthcare'),
  TopCompany(rank: 195, name: 'Manipal Hospitals', industry: 'Healthcare'),
  TopCompany(rank: 196, name: 'Narayana Health', industry: 'Healthcare'),
  TopCompany(rank: 197, name: 'Medanta', industry: 'Healthcare'),
  TopCompany(rank: 198, name: 'Metropolis Healthcare', industry: 'Diagnostics'),
  TopCompany(rank: 199, name: 'Dr Lal PathLabs', industry: 'Diagnostics'),
  TopCompany(rank: 200, name: 'Reliance Retail', industry: 'Retail'),
  TopCompany(rank: 201, name: 'DMart / Avenue Supermarts', industry: 'Retail'),
  TopCompany(rank: 202, name: 'Trent', industry: 'Retail'),
  TopCompany(rank: 203, name: 'Shoppers Stop', industry: 'Retail'),
  TopCompany(rank: 204, name: 'Aditya Birla Fashion & Retail', industry: 'Retail'),
  TopCompany(rank: 205, name: 'Lifestyle International', industry: 'Retail'),
  TopCompany(rank: 206, name: 'Flipkart', industry: 'E-commerce'),
  TopCompany(rank: 207, name: 'Amazon India', industry: 'E-commerce'),
  TopCompany(rank: 208, name: 'Myntra', industry: 'E-commerce'),
  TopCompany(rank: 209, name: 'Meesho', industry: 'E-commerce'),
  TopCompany(rank: 210, name: 'Nykaa', industry: 'E-commerce / Beauty'),
  TopCompany(rank: 211, name: 'Swiggy', industry: 'Food Tech / Delivery'),
  TopCompany(rank: 212, name: 'Zomato', industry: 'Food Tech / Delivery'),
  TopCompany(rank: 213, name: 'Zepto', industry: 'Quick Commerce'),
  TopCompany(rank: 214, name: 'Blinkit', industry: 'Quick Commerce'),
  TopCompany(rank: 215, name: 'Bharti Airtel', industry: 'Telecom'),
  TopCompany(rank: 216, name: 'Reliance Jio', industry: 'Telecom / Digital'),
  TopCompany(rank: 217, name: 'Vodafone Idea', industry: 'Telecom'),
  TopCompany(rank: 218, name: 'Tata Communications', industry: 'Telecom / Digital'),
  TopCompany(rank: 219, name: 'Network18', industry: 'Media'),
  TopCompany(rank: 220, name: 'Disney Star India', industry: 'Media'),
  TopCompany(rank: 221, name: 'Sony Pictures Networks India', industry: 'Media'),
  TopCompany(rank: 222, name: 'Zee Entertainment Enterprises', industry: 'Media'),
  TopCompany(rank: 223, name: 'Indian Railways', industry: 'Rail / Transport'),
  TopCompany(rank: 224, name: 'Air India', industry: 'Aviation'),
  TopCompany(rank: 225, name: 'IndiGo', industry: 'Aviation'),
  TopCompany(rank: 226, name: 'Akasa Air', industry: 'Aviation'),
  TopCompany(rank: 227, name: 'MakeMyTrip', industry: 'Travel Tech'),
  TopCompany(rank: 228, name: 'Thomas Cook India', industry: 'Travel'),
  TopCompany(rank: 229, name: 'Blue Dart', industry: 'Logistics'),
  TopCompany(rank: 230, name: 'Delhivery', industry: 'Logistics'),
  TopCompany(rank: 231, name: 'Ecom Express', industry: 'Logistics'),
  TopCompany(rank: 232, name: 'DHL Express India', industry: 'Logistics'),
  TopCompany(rank: 233, name: 'FedEx India', industry: 'Logistics'),
  TopCompany(rank: 234, name: 'Mahindra Logistics', industry: 'Logistics'),
  TopCompany(rank: 235, name: 'TCI - Transport Corporation of India', industry: 'Logistics'),
  TopCompany(rank: 236, name: 'Oberoi Group', industry: 'Hospitality'),
  TopCompany(rank: 237, name: 'ITC Hotels', industry: 'Hospitality'),
  TopCompany(rank: 238, name: 'Indian Hotels Company (IHCL)', industry: 'Hospitality'),
  TopCompany(rank: 239, name: 'Marriott International India', industry: 'Hospitality'),
  TopCompany(rank: 240, name: 'Hilton India', industry: 'Hospitality'),
  TopCompany(rank: 241, name: 'Deloitte India', industry: 'Professional Services'),
  TopCompany(rank: 242, name: 'PwC India', industry: 'Professional Services'),
  TopCompany(rank: 243, name: 'EY India', industry: 'Professional Services'),
  TopCompany(rank: 244, name: 'KPMG India', industry: 'Professional Services'),
  TopCompany(rank: 245, name: 'Grant Thornton Bharat', industry: 'Professional Services'),
  TopCompany(rank: 246, name: 'CBRE India', industry: 'Real Estate Services'),
  TopCompany(rank: 247, name: 'JLL India', industry: 'Real Estate Services'),
  TopCompany(rank: 248, name: 'SBI General Insurance', industry: 'Insurance'),
  TopCompany(rank: 249, name: 'ICICI Lombard General Insurance', industry: 'Insurance'),
  TopCompany(rank: 250, name: 'Bajaj Allianz General Insurance', industry: 'Insurance'),
];
