import '../../core/models/learning_resource.dart';

/// The Learning Resources Library — every entry verified live against the
/// provider's own site (not recited from memory) before being added here,
/// per the same discipline `ai_course.dart` established for `kAiCourses`.
/// Roughly half of this list was seeded from a pre-researched source
/// catalogue; the rest was added and individually verified this session to
/// fill categories that catalogue under-covered (HR, corporate governance
/// and security, and a materially deeper AI & Generative AI section).
const List<LearningResource> kLearningResources = [
  // ---------------------------------------------------------------------
  // AI & Generative AI
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'openai-academy',
    name: 'OpenAI Academy courses',
    provider: 'OpenAI',
    url: 'https://academy.openai.com/',
    category: 'AI & Generative AI',
    tags: ['ai literacy', 'prompting', 'ai at work', 'chatgpt', 'ai adoption', 'generative ai'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, short modules',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Free, self-paced courses on using AI at work, building with AI, and leading AI '
        'adoption — with separate tracks for different roles. Free certificate of completion for '
        'anyone with a ChatGPT account.',
    practicalProject: 'Use ChatGPT to draft, then improve, a real weekly status report you already owe someone.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'microsoft-learn-ai-copilot',
    name: 'AI & Copilot learning',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-in/training/',
    category: 'AI & Generative AI',
    tags: ['ai literacy', 'copilot', 'productivity', 'microsoft 365'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, modular',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Official, self-paced Microsoft learning covering AI literacy and Copilot use across '
        'Microsoft 365 — the natural starting point if your target employer already runs on Microsoft.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'microsoft-copilot-get-started',
    name: 'Get started with Microsoft 365 Copilot',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/courses/get-started-microsoft-365-copilot-1hr',
    category: 'AI & Generative AI',
    tags: ['copilot', 'microsoft 365', 'prompting', 'word', 'excel', 'powerpoint'],
    level: 'Beginner',
    duration: '1 hour',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A focused, one-hour module on using Copilot inside Word, Excel, PowerPoint, Teams and '
        'Outlook — the fastest way to become immediately useful with Copilot in a Microsoft-shop office.',
    practicalProject: 'Use Copilot to draft a PowerPoint deck from a set of bullet points you already have.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'azure-ai-900',
    name: 'Azure AI Fundamentals (AI-900)',
    provider: 'Microsoft',
    url: 'https://learn.microsoft.com/en-us/training/courses/ai-901t00',
    category: 'AI & Generative AI',
    tags: ['ai fundamentals', 'azure ai', 'cloud ai'],
    level: 'Beginner',
    duration: 'Self-paced learning + a proctored exam',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'Foundational, vendor-neutral-in-content AI concepts (machine learning, computer '
        'vision, NLP, generative AI) with an optional Microsoft certification exam — a credible entry '
        'certification for a technology or digital-transformation role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'aws-skill-builder-genai',
    name: 'Generative AI / AI Practitioner learning',
    provider: 'AWS Skill Builder',
    url: 'https://aws.amazon.com/training/digital/',
    category: 'AI & Generative AI',
    tags: ['generative ai', 'ai practitioner', 'cloud ai', 'aws'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, 1,000+ resources',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: '1,000+ free AWS learning resources on generative AI and AI-practitioner skills, with '
        'paid certification options for those targeting a cloud/AI-enablement role specifically.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-skills-genai',
    name: 'Generative AI learning paths',
    provider: 'Google Skills',
    url: 'https://www.skills.google/',
    category: 'AI & Generative AI',
    tags: ['generative ai', 'ai transformation', 'google cloud', 'digital transformation'],
    level: 'Beginner–Advanced',
    duration: 'Self-paced, ~3,000 resources',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: "Google's unified learning platform — nearly 3,000 courses and labs spanning "
        'generative AI, Google Cloud and Google DeepMind content, from non-technical AI awareness '
        'through hands-on technical labs.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-skills-intro-genai',
    name: 'Introduction to Generative AI',
    provider: 'Google Skills',
    url: 'https://www.skills.google/paths/118',
    category: 'AI & Generative AI',
    tags: ['generative ai', 'ai fundamentals', 'llms', 'non-technical ai'],
    level: 'Beginner',
    duration: 'About 45 minutes',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A short, non-technical generative-AI primer aimed explicitly at sales, marketing, HR '
        'and operations roles — a genuinely fast way to hold your own in a first conversation about AI.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'ibm-skillsbuild-ai',
    name: 'AI foundations',
    provider: 'IBM SkillsBuild',
    url: 'https://skillsbuild.org/',
    category: 'AI & Generative AI',
    tags: ['ai literacy', 'responsible ai', 'digital skills'],
    level: 'Beginner',
    duration: 'Self-paced, part of 1,000+ courses',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Free foundational AI and digital-skills courses from IBM, with IBM-branded digital '
        'credentials — a solid, no-cost credential to list alongside your CV.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'deeplearningai-genai',
    name: 'GenAI / prompting short courses',
    provider: 'DeepLearning.AI',
    url: 'https://www.deeplearning.ai/courses/',
    category: 'AI & Generative AI',
    tags: ['generative ai', 'prompting', 'llm application', 'andrew ng'],
    level: 'Beginner–Advanced',
    duration: 'Short courses, 1–7 hours each',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Short, practical, technically credible generative-AI courses (many by Andrew Ng) — '
        'the best next step once you want more depth than a one-hour awareness module.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'deeplearningai-prompting-for-everyone',
    name: 'AI Prompting for Everyone',
    provider: 'DeepLearning.AI',
    url: 'https://www.deeplearning.ai/courses/ai-prompting-for-everyone/',
    category: 'AI & Generative AI',
    tags: ['prompting', 'generative ai', 'thought partner', 'andrew ng'],
    level: 'Beginner',
    duration: '7h4m, 21 video lessons',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Taught by Andrew Ng — finding information, using AI as a thought partner, and working '
        'with multimedia. Free to watch; certificate needs a paid membership.',
    practicalProject: 'Use AI as a thought partner to red-team your own CV-vs-JD fit before applying.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'vanderbilt-prompt-engineering-chatgpt',
    name: 'Prompt Engineering for ChatGPT',
    provider: 'Vanderbilt University (Coursera)',
    url: 'https://www.coursera.org/learn/prompt-engineering',
    category: 'AI & Generative AI',
    tags: ['prompting', 'chatgpt', 'llms', 'prompt engineering'],
    level: 'Beginner',
    duration: 'Six modules, self-paced',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'A structured, university-taught progression from basic prompts to sophisticated '
        'ones — one of the most widely completed prompt-engineering courses on Coursera, free to audit.',
    practicalProject: 'Write and iterate a multi-step prompt that produces a full first-draft board note.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-prompting-essentials',
    name: 'Google Prompting Essentials',
    provider: 'Google (Coursera)',
    url: 'https://www.coursera.org/specializations/prompting-essentials-google',
    category: 'AI & Generative AI',
    tags: ['prompting', 'gemini', 'generative ai', 'google workspace'],
    level: 'Beginner',
    duration: 'Under 10 hours',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'A 5-step framework for writing effective prompts, taught with Gemini and Google '
        'Workspace but explicitly transferable to any generative-AI tool. Not aimed at a prompt-engineer '
        'job — aimed at everyday output quality.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'anthropic-academy',
    name: 'Anthropic Academy',
    provider: 'Anthropic',
    url: 'https://www.anthropic.com/learn',
    category: 'AI & Generative AI',
    tags: ['claude', 'ai fluency', 'generative ai', 'ai at work'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, 13 short courses',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: "Anthropic's own free training platform for Claude — a no-code \"AI Fluency\" track for "
        'everyday work use, plus developer-focused tracks if the target role needs technical depth. Free '
        'certificate on completion, no Anthropic account required.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'nvidia-dli-free-courses',
    name: 'Deep Learning Institute (DLI) free self-paced courses',
    provider: 'NVIDIA',
    url: 'https://learn.nvidia.com/self-paced-courses',
    category: 'AI & Generative AI',
    tags: ['deep learning', 'ai fundamentals', 'generative ai', 'data science'],
    level: 'Beginner',
    duration: 'Under 8 hours per course',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: '21 genuinely free, self-paced NVIDIA courses spanning AI fundamentals, generative AI '
        'and data science, most completable in a day or less, with a certificate of competency on '
        'select courses.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'soar-skill-india',
    name: 'SOAR (Skilling for AI Readiness)',
    provider: 'Ministry of Skill Development & Entrepreneurship, Government of India',
    url: 'https://www.skillindiadigital.gov.in/',
    category: 'AI & Generative AI',
    tags: ['ai readiness', 'micro-credential', 'india', 'skill india'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, 50 NSQF-aligned micro-credential courses',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A national AI-readiness initiative on the Skill India Digital Hub, developed with '
        'industry partners including Microsoft and NASSCOM — a free, India-context AI credential.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Data & Analytics
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'ms-learn-data-analytics-path',
    name: 'Get started with Microsoft data analytics',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/data-analytics-microsoft/',
    category: 'Data & Analytics',
    tags: ['power bi', 'analytics', 'dashboards', 'data'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced learning path',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A structured, official Microsoft learning path into data analytics and Power BI — the '
        'right starting point before any specific Power BI module below.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'ms-learn-power-bi-prepare-visualize',
    name: 'Prepare and visualize data with Power BI',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/prepare-visualize-data-power-bi/',
    category: 'Data & Analytics',
    tags: ['power bi', 'power query', 'visualization', 'dashboards'],
    level: 'Beginner',
    duration: 'Self-paced learning path',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Hands-on, beginner-level path covering Power Query and first visualizations — the '
        'fastest route to a working Power BI dashboard.',
    practicalProject: 'Build a one-page operations or headcount dashboard from a sample dataset.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'ms-learn-power-bi-reports',
    name: 'Design effective reports in Power BI',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/power-bi-effective/',
    category: 'Data & Analytics',
    tags: ['power bi', 'data storytelling', 'dashboards', 'reporting'],
    level: 'Intermediate',
    duration: 'Self-paced learning path',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Report design and data-storytelling once you already know the Power BI basics — '
        'takes a working dashboard and makes it one leadership will actually read.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-data-analytics-cert',
    name: 'Google Data Analytics Professional Certificate',
    provider: 'Google (Coursera)',
    url: 'https://grow.google/certificates/data-analytics/',
    category: 'Data & Analytics',
    tags: ['data analysis', 'sql', 'spreadsheets', 'visualization'],
    level: 'Beginner–Intermediate',
    duration: 'A few months, self-paced',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'A career-oriented, structured pathway across spreadsheets, SQL and visualization — '
        'the fuller alternative to piecing together free modules if you want one recognised credential.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'ibm-data-analyst-cert',
    name: 'IBM Data Analyst Professional Certificate',
    provider: 'IBM (Coursera)',
    url: 'https://www.coursera.org/professional-certificates/ibm-data-analyst',
    category: 'Data & Analytics',
    tags: ['excel', 'sql', 'python', 'data visualization'],
    level: 'Beginner–Intermediate',
    duration: 'A few months, self-paced',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'A broad analyst pathway across Excel, SQL and Python — a good fit if your target role '
        'wants breadth across tools rather than deep specialism in one.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'kaggle-learn',
    name: 'Kaggle Learn',
    provider: 'Kaggle',
    url: 'https://www.kaggle.com/learn',
    category: 'Data & Analytics',
    tags: ['python', 'pandas', 'sql', 'data science'],
    level: 'Beginner–Intermediate',
    duration: 'Short, practical exercises',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Short, hands-on exercises in Python, pandas and SQL with real notebooks — good for '
        'building muscle memory once the concepts are understood elsewhere.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'freecodecamp-data-analysis-python',
    name: 'Data Analysis with Python Certification',
    provider: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
    category: 'Data & Analytics',
    tags: ['python', 'pandas', 'numpy', 'matplotlib', 'data analysis'],
    level: 'Beginner–Intermediate',
    duration: 'Around 170 hours across five projects',
    cost: ResourceCost.free,
    resourceType: ResourceType.certification,
    description: 'A genuinely free, project-based certification covering NumPy, Pandas, Matplotlib and '
        'Seaborn on real datasets — thorough, but a serious time investment, not a quick primer.',
    practicalProject: 'Complete the certification\'s five capstone data-analysis projects.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'tableau-learning',
    name: 'Tableau learning',
    provider: 'Tableau',
    url: 'https://www.tableau.com/learn/training',
    category: 'Data & Analytics',
    tags: ['tableau', 'business intelligence', 'data visualization'],
    level: 'Beginner–Advanced',
    duration: 'Self-paced + instructor-led options',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Official Tableau training resources — worth it specifically when a target JD names '
        'Tableau rather than Power BI, since the two aren\'t identical skill sets in a recruiter\'s eyes.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'sqlbolt',
    name: 'SQL lessons',
    provider: 'SQLBolt',
    url: 'https://sqlbolt.com/',
    category: 'Data & Analytics',
    tags: ['sql', 'databases', 'query'],
    level: 'Beginner',
    duration: 'A few hours, interactive',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: 'Free, interactive, in-browser SQL practice — the fastest way to become genuinely '
        'comfortable writing SQL queries rather than just recognising them.',
    practicalProject: 'Write and run 10 real queries against the interactive practice database.',
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Project & Programme Management
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'pmi-pmp',
    name: 'PMP certification',
    provider: 'PMI',
    url: 'https://www.pmi.org/certifications/project-management-pmp',
    category: 'Project & Programme Management',
    tags: ['project management', 'pmp'],
    level: 'Advanced / experienced',
    duration: 'Exam prep varies; eligibility applies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The major professional project-management credential — check military project '
        'experience against PMI\'s published eligibility criteria before committing; not every officer '
        'qualifies without first building a documented track record.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'pmi-capm',
    name: 'CAPM certification',
    provider: 'PMI',
    url: 'https://www.pmi.org/certifications/certified-associate-capm',
    category: 'Project & Programme Management',
    tags: ['project management', 'capm', 'entry level'],
    level: 'Beginner–Intermediate',
    duration: 'Exam prep varies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The entry/early-career PMI credential — the right first step when PMP eligibility '
        "isn't yet met, rather than waiting idle for experience to accrue.",
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'pmi-learning',
    name: 'PMI learning resources',
    provider: 'PMI',
    url: 'https://www.pmi.org/learning',
    category: 'Project & Programme Management',
    tags: ['project management', 'agile', 'pmi'],
    level: 'Beginner–Advanced',
    duration: 'Self-paced, varies',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Official PMI learning and exam-prep resources covering PM methods, Agile and the '
        'business environment.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-project-management-cert',
    name: 'Google Project Management: Professional Certificate',
    provider: 'Google (Coursera)',
    url: 'https://www.coursera.org/professional-certificates/google-project-management',
    category: 'Project & Programme Management',
    tags: ['project management', 'agile', 'scrum', 'entry level'],
    level: 'Beginner',
    duration: 'About 6 months at 10 hours/week',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'A practical, entry-level project-management pathway covering traditional and Agile '
        'methods, with hands-on documentation and Scrum foundations — a good CAPM alternative if the '
        'target role values applied over theoretical PM knowledge.',
    practicalProject: 'Build a full project charter and RAID log for a simulated project, as the course requires.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'atlassian-agile',
    name: 'Agile learning',
    provider: 'Atlassian',
    url: 'https://www.atlassian.com/agile',
    category: 'Project & Programme Management',
    tags: ['agile', 'jira', 'scrum', 'team workflows'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced articles and guides',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: 'Practical, tool-grounded Agile concepts from the company that makes Jira — useful '
        'specifically because it teaches the workflow you\'ll actually be asked to use, not just the '
        'theory.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'scrum-org-learning',
    name: 'Professional Scrum learning',
    provider: 'Scrum.org',
    url: 'https://www.scrum.org/',
    category: 'Project & Programme Management',
    tags: ['scrum', 'agile'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced + certification exams',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'The official Scrum learning and certification body — worth the paid Professional '
        'Scrum Master credential specifically for technology/transformation-adjacent roles.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Operations & Supply Chain
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'nptel-operations-scm',
    name: 'Operations and Supply Chain Management (IIT Madras)',
    provider: 'NPTEL',
    url: 'https://www.nptel.ac.in/courses/110106045',
    category: 'Operations & Supply Chain',
    tags: ['operations', 'supply chain', 'quantitative methods', 'iit'],
    level: 'Beginner–Intermediate',
    duration: 'A full academic-term course, free to audit',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'An IIT Madras-backed operations and supply-chain course — a credible, India-context '
        'free foundation with an optional paid certificate.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'mit-ocw-intro-operations-management',
    name: 'Introduction to Operations Management',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/15-760b-introduction-to-operations-management-spring-2004/',
    category: 'Operations & Supply Chain',
    tags: ['operations', 'process analysis', 'quality management', 'product development'],
    level: 'Intermediate',
    duration: 'A half-term MIT Sloan course, self-paced',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: 'Full MIT Sloan course materials — process analysis, quality management, supply-chain '
        'design and procurement — genuinely free, no certificate, pure course content.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'mit-ocw-logistics-scm',
    name: 'Logistics and Supply Chain Management',
    provider: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/courses/esd-273j-logistics-and-supply-chain-management-fall-2009/',
    category: 'Operations & Supply Chain',
    tags: ['logistics', 'supply chain', 'inventory', 'distribution'],
    level: 'Intermediate–Advanced',
    duration: 'A full-term MIT course, self-paced',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: 'Full MIT Engineering Systems Division course materials on logistics network design '
        'and supply-chain strategy — deeper and more quantitative than most free alternatives.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'ascm-cpim',
    name: 'CPIM',
    provider: 'ASCM',
    url: 'https://www.ascm.org/credentials-education/certifications/cpim/',
    category: 'Operations & Supply Chain',
    tags: ['inventory', 'production planning', 'operations'],
    level: 'Intermediate–Advanced',
    duration: 'Exam prep varies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'A professional planning/inventory/production credential — consider this before CSCP '
        'if the target role is planning-heavy rather than end-to-end supply-chain leadership.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'ascm-cscp',
    name: 'CSCP',
    provider: 'ASCM',
    url: 'https://www.ascm.org/credentials-education/certifications/cscp/',
    category: 'Operations & Supply Chain',
    tags: ['supply chain', 'end to end'],
    level: 'Intermediate–Advanced',
    duration: 'Exam prep varies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The end-to-end supply-chain credential — the stronger choice for a Supply Chain '
        'Manager-level target role rather than a purely planning-focused one.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'lean-enterprise-institute',
    name: 'Lean learning',
    provider: 'Lean Enterprise Institute',
    url: 'https://www.lean.org/',
    category: 'Operations & Supply Chain',
    tags: ['lean', 'continuous improvement', 'manufacturing'],
    level: 'Beginner–Advanced',
    duration: 'Self-paced articles, workshops and paid courses',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Lean principles and practical resources from the institute most closely associated '
        'with the discipline — a strong companion to Six Sigma for a manufacturing/operations target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Quality & Process Improvement
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'asq-certifications',
    name: 'Quality / Six Sigma certifications',
    provider: 'ASQ',
    url: 'https://asq.org/certification',
    category: 'Quality & Process Improvement',
    tags: ['quality', 'six sigma', 'process improvement'],
    level: 'Beginner–Advanced',
    duration: 'Exam prep varies by level',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'Professional quality-credential pathways from the American Society for Quality — the '
        'recognised body for a Quality Manager or Six Sigma Black Belt-level target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'simplilearn-six-sigma-basics',
    name: 'Six Sigma basics (free course)',
    provider: 'Simplilearn',
    url: 'https://www.simplilearn.com/learn-six-sigma-basics-free-course-skillup',
    category: 'Quality & Process Improvement',
    tags: ['six sigma', 'lean', 'process improvement', 'free'],
    level: 'Beginner',
    duration: '7 hours, self-paced',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A genuinely free 7-hour Six Sigma primer — the right first step before deciding '
        'whether a paid ASQ or Green Belt certification is actually worth pursuing for your target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Procurement
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'cips-qualifications',
    name: 'CIPS qualifications',
    provider: 'CIPS',
    url: 'https://www.cips.org/qualifications',
    category: 'Procurement',
    tags: ['procurement', 'sourcing', 'commercial management'],
    level: 'Beginner–Advanced',
    duration: 'Modular; months to complete a full level',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The globally recognised professional procurement qualification pathway — the credible '
        'choice for a Procurement Manager or commercial-management target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'sap-procurement-learning',
    name: 'Sourcing / Procurement learning',
    provider: 'SAP Learning',
    url: 'https://learning.sap.com/learning-journeys',
    category: 'Procurement',
    tags: ['sap', 'procurement', 's/4hana', 'sourcing'],
    level: 'Beginner–Advanced',
    duration: 'Self-paced learning journeys',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Official SAP learning journeys for sourcing and procurement — worth prioritising '
        "when a target JD names SAP specifically, since it's the single most common ERP in Indian "
        'corporate procurement.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'gem-training',
    name: 'GeM (Government e-Marketplace) official training',
    provider: 'Government of India',
    url: 'https://gem.gov.in/training',
    category: 'Procurement',
    tags: ['gem', 'government procurement', 'india', 'public procurement'],
    level: 'Beginner',
    duration: 'Self-paced modules and step-by-step guides',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: "The government's own training for India's National Public Procurement Portal — "
        'directly relevant for any target role involving PSU or government procurement, and often '
        'overlooked in generic procurement study plans.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'iimm-certification',
    name: 'IIMM certification programme',
    provider: 'Indian Institute of Materials Management',
    url: 'https://iimm.org/levels-of-certification/',
    category: 'Procurement',
    tags: ['materials management', 'supply chain', 'procurement', 'india'],
    level: 'Beginner–Advanced',
    duration: 'Diploma (6 months) up to a 2-year PG diploma',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: "India's national apex body for materials/supply-chain management — its Diploma and "
        'PG Diploma in Materials Management are well recognised across Indian manufacturing and PSUs, '
        'and often a more India-market-relevant credential than the global CIPS/ASCM options above.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Finance & Commercial Acumen
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'khan-academy-finance',
    name: 'Finance and capital markets',
    provider: 'Khan Academy',
    url: 'https://www.khanacademy.org/economics-finance-domain/core-finance',
    category: 'Finance & Commercial Acumen',
    tags: ['finance fundamentals', 'capital markets', 'basics'],
    level: 'Beginner',
    duration: 'Self-paced video lessons',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: 'A genuinely good, free foundation in finance and capital markets for an officer with '
        'no prior finance exposure — start here before anything else in this category.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'coursera-finance-for-non-finance',
    name: 'Finance for Non-Finance',
    provider: 'Coursera',
    url: 'https://www.coursera.org/courses?query=finance%20for%20non%20finance',
    category: 'Finance & Commercial Acumen',
    tags: ['p&l', 'financial statements', 'business finance', 'non-finance managers'],
    level: 'Beginner',
    duration: 'Varies by course, typically weeks',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Targeted business-finance learning aimed at exactly the audience this app serves — '
        'managers who need P&L and financial-statement fluency without becoming accountants.',
    practicalProject: 'Analyse a public company\'s annual report and prepare a one-page management summary.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'yale-financial-markets',
    name: 'Financial Markets',
    provider: 'Yale University (Coursera)',
    url: 'https://www.coursera.org/learn/financial-markets-global',
    category: 'Finance & Commercial Acumen',
    tags: ['financial markets', 'risk', 'securities', 'banking'],
    level: 'Beginner–Intermediate',
    duration: '23 lectures, free to audit',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Nobel laureate Robert Shiller\'s Yale course on how societies manage risk through '
        'securities, insurance and banking — genuinely free to watch, deeper and more theory-grounded '
        'than most "finance for managers" content.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'cfi-financial-modeling',
    name: 'Financial Modeling & Valuation',
    provider: 'CFI (Corporate Finance Institute)',
    url: 'https://corporatefinanceinstitute.com/',
    category: 'Finance & Commercial Acumen',
    tags: ['financial modeling', 'excel', 'valuation'],
    level: 'Intermediate–Advanced',
    duration: 'Self-paced, varies by certification track',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'Practical, Excel-heavy financial-modelling and valuation training — worth the cost '
        'specifically for a Strategy, Finance or Business Development target role, not a general '
        'finance-literacy need.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'cfa-institute-learning',
    name: 'Investment foundations / finance learning',
    provider: 'CFA Institute',
    url: 'https://www.cfainstitute.org/',
    category: 'Finance & Commercial Acumen',
    tags: ['finance', 'investments', 'ethics'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced + a multi-level charter programme',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'Recognised finance and investment learning resources from the body behind the CFA '
        'charter — only pursue the full charter if the target role is genuinely investment/finance-led, '
        'given its multi-year commitment.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'nse-academy-ncfm',
    name: 'NCFM (Certification in Financial Markets)',
    provider: 'NSE Academy',
    url: 'https://www.nseindia.com/static/learn/self-study-ncfm-modules-all',
    category: 'Finance & Commercial Acumen',
    tags: ['financial markets', 'india', 'nse'],
    level: 'Beginner–Advanced',
    duration: 'Self-study modules, each with its own exam',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: "The National Stock Exchange's own applied, module-based financial-markets "
        'certification — no formal eligibility criteria, over 200 exam centres across India, and a '
        'practically oriented alternative to CFA for an India-market financial-services target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Strategy & Leadership
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'nptel-strategic-management',
    name: 'Strategic Management / management courses',
    provider: 'NPTEL',
    url: 'https://nptel.ac.in/',
    category: 'Strategy & Leadership',
    tags: ['strategy', 'management', 'india', 'leadership'],
    level: 'Beginner–Advanced',
    duration: 'Full academic-term courses, free to audit',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'India\'s national academic learning platform, backed by the IITs and IISc — a '
        'credible, no-cost strategy foundation before considering paid executive education.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'hbr-management-strategy',
    name: 'Management and strategy resources',
    provider: 'Harvard Business Review',
    url: 'https://hbr.org/',
    category: 'Strategy & Leadership',
    tags: ['leadership', 'strategy', 'management', 'case studies'],
    level: 'Intermediate–Advanced',
    duration: 'Ongoing reading, self-paced',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.studyMaterial,
    description: 'High-quality management thinking and case studies — the right ongoing habit for a '
        'senior target role rather than a one-time course to complete.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'mckinsey-insights',
    name: 'Strategy / transformation insights',
    provider: 'McKinsey & Company',
    url: 'https://www.mckinsey.com/featured-insights',
    category: 'Strategy & Leadership',
    tags: ['strategy', 'transformation', 'operations', 'consulting'],
    level: 'Intermediate–Advanced',
    duration: 'Ongoing reading, self-paced',
    cost: ResourceCost.free,
    resourceType: ResourceType.studyMaterial,
    description: 'Free, current management perspectives and case examples — useful for sounding '
        'genuinely current on strategy/transformation in an interview, not a substitute for a course.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'harvard-online-leadership',
    name: 'Leadership / negotiation / strategy',
    provider: 'Harvard Online',
    url: 'https://pll.harvard.edu/',
    category: 'Strategy & Leadership',
    tags: ['leadership', 'negotiation', 'executive education', 'strategy'],
    level: 'Intermediate–Advanced',
    duration: 'Weeks, self-paced or cohort-based',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'Premium, genuinely Harvard-taught executive learning — reserve this for a real, '
        'specific gap a senior target role demands, not as a default first step.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'coursera-strategic-leadership-illinois',
    name: 'Strategic Leadership and Management Specialization',
    provider: 'University of Illinois Urbana-Champaign (Coursera)',
    url: 'https://www.coursera.org/specializations/strategic-leadership',
    category: 'Strategy & Leadership',
    tags: ['leadership', 'strategy', 'organizational management'],
    level: 'Intermediate',
    duration: '6-course specialization, self-paced',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'A structured 6-course specialization on leading people, teams and organisations, '
        'ending in a capstone leadership-and-management plan applied to a real business situation.',
    practicalProject: 'Complete the specialization\'s capstone leadership-and-management plan for a business situation.',
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Business Communication
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'coursera-business-communication',
    name: 'Business Communication courses',
    provider: 'Coursera',
    url: 'https://www.coursera.org/courses?query=business%20communication',
    category: 'Business Communication',
    tags: ['business writing', 'presentations', 'communication'],
    level: 'Beginner–Intermediate',
    duration: 'Varies by course',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'Practical corporate communication courses across writing, presenting and everyday '
        'workplace communication.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'coursera-business-writing-cu-boulder',
    name: 'Business Writing',
    provider: 'University of Colorado Boulder (Coursera)',
    url: 'https://www.coursera.org/learn/writing-for-business',
    category: 'Business Communication',
    tags: ['business writing', 'email', 'clarity', 'structure'],
    level: 'Beginner–Intermediate',
    duration: 'A few weeks, self-paced',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Ten specific principles of good business writing with simple, immediately usable '
        'tools — a sharper, more concrete alternative to a general "communication skills" course.',
    practicalProject: 'Rewrite your last three real work emails applying the course\'s top-ten principles.',
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'linkedin-learning-business-communication',
    name: 'Business communication learning',
    provider: 'LinkedIn Learning',
    url: 'https://www.linkedin.com/learning/',
    category: 'Business Communication',
    tags: ['email', 'presentations', 'communication', 'library'],
    level: 'Beginner–Intermediate',
    duration: 'Short video courses, self-paced',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'A large, practical learning library covering email, presentations and workplace '
        'communication — a subscription, so worth it mainly if the target employer already provides '
        'access.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'toastmasters',
    name: 'Public speaking / leadership practice',
    provider: 'Toastmasters International',
    url: 'https://www.toastmasters.org/',
    category: 'Business Communication',
    tags: ['presentation', 'public speaking', 'confidence'],
    level: 'Beginner–Advanced',
    duration: 'Ongoing club membership',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'Practice-led communication development through a real local club, not a video course '
        '— the right choice specifically when the gap is speaking confidence under scrutiny, not '
        'knowledge of communication theory.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // HR & People
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'shrm-cp-scp',
    name: 'SHRM-CP / SHRM-SCP',
    provider: 'SHRM',
    url: 'https://www.shrm.org/in/credentials/certification',
    category: 'HR & People',
    tags: ['hr', 'human resources', 'strategic hr'],
    level: 'Intermediate–Advanced',
    duration: 'Exam prep varies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'Recognised HR credentials — SHRM-CP for operational HR, SHRM-SCP for strategic HR '
        'leadership; choose based on whether the target role is HR execution or HR strategy.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'hrci-aphr',
    name: 'Associate Professional in Human Resources (aPHR)',
    provider: 'HRCI',
    url: 'https://www.hrci.org/certifications/individual-certifications',
    category: 'HR & People',
    tags: ['hr', 'human resources', 'entry level'],
    level: 'Beginner',
    duration: '3-hour, 175-question exam',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The right entry point for an officer moving into HR with no prior HR experience — '
        'unlike SHRM-CP, it requires no professional HR background, only foundational knowledge across '
        'talent acquisition, compensation and compliance.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'coursera-human-resources',
    name: 'Human Resources courses',
    provider: 'Coursera',
    url: 'https://www.coursera.org/courses?query=human%20resources',
    category: 'HR & People',
    tags: ['hr fundamentals', 'talent', 'employee relations'],
    level: 'Beginner–Intermediate',
    duration: 'Varies by course',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: 'A foundation across HR fundamentals, talent management and employee relations for an '
        'officer transitioning into an HR/people function.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'nhrdn',
    name: 'National HRD Network — membership & certification programmes',
    provider: 'National HRD Network',
    url: 'https://www.nationalhrd.org/',
    category: 'HR & People',
    tags: ['hr', 'india', 'networking', 'talent acquisition'],
    level: 'Beginner–Advanced',
    duration: 'Ongoing membership plus specific programmes',
    cost: ResourceCost.paid,
    resourceType: ResourceType.course,
    description: "India's largest HR professional network — over 21,000 members across 61 city "
        'chapters — valuable as much for its India-specific HR community and events as for its formal '
        'upskilling programmes.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // IT & Cloud
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'aws-cloud-practitioner',
    name: 'AWS Cloud Practitioner learning',
    provider: 'AWS Skill Builder',
    url: 'https://aws.amazon.com/training/',
    category: 'IT & Cloud',
    tags: ['cloud fundamentals', 'aws'],
    level: 'Beginner',
    duration: 'Free learning; certification optional',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'Free foundational cloud learning with an optional AWS certification — a good starting '
        'credential for a digital-transformation or IT-adjacent management role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'azure-fundamentals-az900',
    name: 'Azure Fundamentals (AZ-900)',
    provider: 'Microsoft Learn',
    url: 'https://learn.microsoft.com/en-us/training/paths/az-900-describe-cloud-concepts/',
    category: 'IT & Cloud',
    tags: ['cloud fundamentals', 'azure'],
    level: 'Beginner',
    duration: 'Free learning; paid exam',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'Official Microsoft cloud-fundamentals learning — the natural choice when a target '
        "employer's stack is Microsoft-centric.",
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-cloud-digital-leader',
    name: 'Cloud Digital Leader',
    provider: 'Google Cloud',
    url: 'https://cloud.google.com/learn/certification/cloud-digital-leader',
    category: 'IT & Cloud',
    tags: ['cloud', 'digital transformation', 'business-oriented'],
    level: 'Beginner',
    duration: 'Free learning; paid exam',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'A business-oriented (not deeply technical) cloud-fundamentals certification — well '
        'suited to a manager who needs to speak credibly about cloud without becoming an engineer.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Cybersecurity
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'isc2-certified-in-cybersecurity',
    name: 'Certified in Cybersecurity (CC)',
    provider: 'ISC2',
    url: 'https://www.isc2.org/certifications/certified-in-cybersecurity',
    category: 'Cybersecurity',
    tags: ['cybersecurity fundamentals', 'entry level'],
    level: 'Beginner',
    duration: 'Free learning offer + paid exam (check current terms)',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.certification,
    description: 'An entry-level professional pathway from one of cybersecurity\'s most recognised '
        'bodies (ISC2, the body behind CISSP) — a credible first cybersecurity credential.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'comptia-security-plus',
    name: 'Security+',
    provider: 'CompTIA',
    url: 'https://www.comptia.org/certifications/security',
    category: 'Cybersecurity',
    tags: ['cybersecurity fundamentals', 'baseline'],
    level: 'Intermediate',
    duration: 'Exam prep varies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'A well-known baseline security certification, widely required as a minimum '
        'qualification in government and defence-adjacent cybersecurity roles specifically.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'cisco-netacad-intro-cybersecurity',
    name: 'Introduction to Cybersecurity',
    provider: 'Cisco Networking Academy',
    url: 'https://www.netacad.com/courses/introduction-to-cybersecurity',
    category: 'Cybersecurity',
    tags: ['cybersecurity fundamentals', 'entry level', 'free'],
    level: 'Beginner',
    duration: 'About 6 hours',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A genuinely free, 6-hour Cisco primer on cybersecurity basics and threat landscape — '
        'the right zero-cost starting point before any paid certification in this category.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'google-cybersecurity-cert',
    name: 'Google Cybersecurity Professional Certificate',
    provider: 'Google (Coursera)',
    url: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    category: 'Cybersecurity',
    tags: ['cybersecurity', 'siem', 'python', 'entry level'],
    level: 'Beginner',
    duration: 'A few months, self-paced, 8 courses',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'An 8-course, job-ready pathway into entry-level cybersecurity roles with hands-on '
        'SIEM, Python, Linux and SQL exposure — no prior experience required, more applied than CC or '
        'Security+ alone.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Sales & CRM
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'salesforce-trailhead',
    name: 'Salesforce / CRM learning',
    provider: 'Salesforce Trailhead',
    url: 'https://trailhead.salesforce.com/',
    category: 'Sales & CRM',
    tags: ['crm', 'salesforce', 'sales process'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, hands-on modules',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'Free, genuinely hands-on Salesforce platform learning — the right choice when a '
        'target JD names Salesforce specifically.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'hubspot-academy-general',
    name: 'Sales / CRM / marketing learning',
    provider: 'HubSpot Academy',
    url: 'https://academy.hubspot.com/',
    category: 'Sales & CRM',
    tags: ['crm', 'sales', 'marketing', 'hubspot'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced, free certifications',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Free certifications and practical modules across sales, marketing and CRM — the '
        'broadest free entry point into a sales/BD target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'hubspot-inbound-sales-cert',
    name: 'Inbound Sales Certification',
    provider: 'HubSpot Academy',
    url: 'https://academy.hubspot.com/courses/inbound-sales',
    category: 'Sales & CRM',
    tags: ['sales', 'inbound sales', 'buyer outreach'],
    level: 'Beginner',
    duration: 'Five classes, ~60-minute exam',
    cost: ResourceCost.free,
    resourceType: ResourceType.certification,
    description: 'A focused, free certification on the inbound-sales methodology — identifying buyers, '
        'outreach and personalised presentations — a strong, specific credential for a first Business '
        'Development role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // ERP & SAP
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'sap-learning-site',
    name: 'SAP Learning site',
    provider: 'SAP Learning',
    url: 'https://learning.sap.com/',
    category: 'ERP & SAP',
    tags: ['sap', 's/4hana', 'erp'],
    level: 'Beginner–Advanced',
    duration: 'Self-paced learning journeys',
    cost: ResourceCost.freeToLearnPaidCertificate,
    resourceType: ResourceType.course,
    description: 'Free self-paced SAP learning plus premium certification options — the starting point '
        'for any SAP-specific gap, whatever the functional area.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'sap-discovering-finance',
    name: 'Discovering Finance (learning journey)',
    provider: 'SAP Learning',
    url: 'https://learning.sap.com/learning-journeys/discovering-finance',
    category: 'ERP & SAP',
    tags: ['sap', 'finance', 's/4hana', 'accounts payable', 'cost management'],
    level: 'Beginner',
    duration: 'Self-paced',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A free overview of SAP Finance — payables/receivables, record-to-report, asset '
        'accounting and cost management — the right first step for a Finance-plus-SAP target role.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),

  // ---------------------------------------------------------------------
  // Corporate Governance & Security
  // ---------------------------------------------------------------------
  LearningResource(
    id: 'asis-cpp',
    name: 'Certified Protection Professional (CPP)',
    provider: 'ASIS International',
    url: 'https://www.asisonline.org/certification/certified-protection-professional-cpp/',
    category: 'Corporate Governance & Security',
    tags: ['corporate security', 'security management', 'senior'],
    level: 'Advanced / senior',
    duration: 'Requires 5-7 years relevant experience; exam prep varies',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The gold-standard generalist security-management credential globally, with ASIS '
        'chapters in 125 countries — the strongest single credential for a Chief Security Officer or '
        'Head of Corporate Security target role. Requires 5-7 years of relevant experience (reduced '
        'with a master\'s degree).',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'acfe-cfe',
    name: 'Certified Fraud Examiner (CFE)',
    provider: 'ACFE',
    url: 'https://www.acfe.com/cfe-credential',
    category: 'Corporate Governance & Security',
    tags: ['fraud', 'internal audit', 'vigilance'],
    level: 'Intermediate–Advanced',
    duration: "Requires a bachelor's degree + 2 years relevant experience; exam prep varies",
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The recognised global credential for fraud detection and deterrence — directly '
        'relevant for a vigilance, internal audit or corporate-investigations target role. Requires '
        'ACFE membership and at least two years of relevant experience.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'iica-independent-directors-databank',
    name: 'Independent Directors Databank',
    provider: 'IICA (Ministry of Corporate Affairs)',
    url: 'https://www.independentdirectorsdatabank.in/',
    category: 'Corporate Governance & Security',
    tags: ['corporate governance', 'board', 'independent director', 'india'],
    level: 'Advanced / senior',
    duration: 'Registration plus a proficiency self-assessment test within 2 years',
    cost: ResourceCost.paid,
    resourceType: ResourceType.certification,
    description: 'The statutory Indian databank a senior officer must register on to be eligible as a '
        "company's Independent Director — directly relevant for a Flag-rank or very senior officer "
        'targeting a board-level or advisory role in India. Requires a Director Identification Number.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
  LearningResource(
    id: 'iso-31000-alison',
    name: 'ISO 31000: Fundamentals of Risk Management',
    provider: 'Alison',
    url: 'https://alison.com/course/iso-31000-the-fundamentals-of-enterprise-risk-management',
    category: 'Corporate Governance & Security',
    tags: ['risk management', 'enterprise risk', 'iso 31000', 'governance'],
    level: 'Beginner–Intermediate',
    duration: 'Self-paced',
    cost: ResourceCost.free,
    resourceType: ResourceType.course,
    description: 'A genuinely free introduction to the ISO 31000 enterprise risk-management framework — '
        'a solid, no-cost foundation before considering a paid PECB or BSI risk-management certification.',
    practicalProject: null,
    lastVerified: '2026-09-12',
  ),
];
