import 'career_vertical.dart';
import 'corps_affinity.dart';

/// How well a Corps/Arm/Branch's typical experience transfers to a given
/// civilian vertical — illustrative guidance, not a verified fact, same
/// framing discipline as the rest of this app's Corps/Arm content.
enum CorpsVerticalFitTier {
  strong('Strong fit'),
  possible('Possible fit'),
  limited('Limited fit'),
  restricted('Restricted');

  const CorpsVerticalFitTier(this.label);
  final String label;
}

/// Editorial fit ratings for the 20 general verticals only, keyed by
/// Corps/Arm/Branch name then vertical name. The 14 medical/legal verticals
/// are deliberately excluded here — they're gated by a real licensing
/// prerequisite, so [corpsVerticalFitTier] resolves those deterministically
/// from [kMedicalCorps]/[kJagCorps] instead of by editorial judgment.
/// "Logistics Branch" and "Education Branch" are shared between the Navy
/// and Air Force entries in `corps_options.dart`, so each appears once here.
const Map<String, Map<String, CorpsVerticalFitTier>> kGeneralVerticalFitByCorps = {
  'Infantry': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.strong,
    'Corporate Investigations': CorpsVerticalFitTier.strong,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
  'Armoured Corps': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.possible,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Regiment of Artillery': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.possible,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Corps of Army Air Defence': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.possible,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.strong,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.possible,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.possible,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Corps of Engineers': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.possible,
    'Integrated Facilities Management': CorpsVerticalFitTier.strong,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.possible,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.possible,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Corps of Signals': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.possible,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.strong,
    'Tech Product & Data Operations': CorpsVerticalFitTier.strong,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.possible,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.strong,
    'Corporate Investigations': CorpsVerticalFitTier.possible,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Army Aviation Corps': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.possible,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Mechanised Infantry': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.possible,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Army Service Corps (ASC)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.strong,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.possible,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Army Ordnance Corps (AOC)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.strong,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.strong,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.possible,
    'Corporate Governance': CorpsVerticalFitTier.possible,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Corps of Electronics & Mechanical Engineers (EME)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.possible,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Army Medical Corps (AMC)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.possible,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Army Dental Corps (ADC)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Military Nursing Service (MNS)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Corps of Military Police (CMP)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.possible,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.possible,
    'Intelligence & Vigilance': CorpsVerticalFitTier.strong,
    'Corporate Investigations': CorpsVerticalFitTier.strong,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
  'Military Intelligence': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.strong,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.possible,
    'Intelligence & Vigilance': CorpsVerticalFitTier.strong,
    'Corporate Investigations': CorpsVerticalFitTier.strong,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
  'Judge Advocate General\'s Department (JAG)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.limited,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.possible,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.strong,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.strong,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.possible,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
  'Army Education Corps (AEC)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.strong,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Army Postal Service (APS)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.strong,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Remount & Veterinary Corps (RVC)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.strong,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Pioneer Corps': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.strong,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Intelligence Corps': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.strong,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.possible,
    'Intelligence & Vigilance': CorpsVerticalFitTier.strong,
    'Corporate Investigations': CorpsVerticalFitTier.strong,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
  'Executive Branch (Seaman/Gunnery/Navigation)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Executive Branch (Air Traffic Control/Observer)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.strong,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Engineering Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Electrical Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.possible,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.strong,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Education Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.strong,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Logistics Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.strong,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.possible,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Medical Branch (Navy)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.possible,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Judge Advocate General\'s Branch (Navy)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.limited,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.possible,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.strong,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.strong,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.possible,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
  'Flying Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.possible,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Technical Branch (Engineering)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.possible,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.strong,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Administration Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.possible,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.strong,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.strong,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.strong,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.possible,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Accounts Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.strong,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.strong,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.possible,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.strong,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Meteorology Branch': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.strong,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.strong,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.possible,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.limited,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.possible,
    'Tech Product & Data Operations': CorpsVerticalFitTier.possible,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.strong,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Medical Branch (Air Force)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.possible,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.possible,
    'Integrated Facilities Management': CorpsVerticalFitTier.possible,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.limited,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.limited,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.limited,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.limited,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.limited,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.limited,
    'Brand Protection & IPR': CorpsVerticalFitTier.limited,
  },
  'Judge Advocate General\'s Branch (Air Force)': {
    'Operations & Process Excellence': CorpsVerticalFitTier.limited,
    'Supply Chain & Procurement': CorpsVerticalFitTier.limited,
    'Security, Risk & Crisis Management': CorpsVerticalFitTier.limited,
    'Integrated Facilities Management': CorpsVerticalFitTier.limited,
    'Aviation, Maritime & Fleet Management': CorpsVerticalFitTier.limited,
    'BFSI & Financial Crime Risk': CorpsVerticalFitTier.possible,
    'Project & Program Management (PMO)': CorpsVerticalFitTier.limited,
    'Strategy, Consulting & Chief of Staff': CorpsVerticalFitTier.possible,
    'Business Development & Strategic Sales': CorpsVerticalFitTier.limited,
    'HR, Talent Management & L&D': CorpsVerticalFitTier.possible,
    'Corporate Affairs, ESG & Public Policy': CorpsVerticalFitTier.strong,
    'Defence PSUs, Offsets & GovTech': CorpsVerticalFitTier.possible,
    'IT Infrastructure & Cybersecurity': CorpsVerticalFitTier.limited,
    'Tech Product & Data Operations': CorpsVerticalFitTier.limited,
    'Manufacturing & Technical Systems': CorpsVerticalFitTier.limited,
    'Aerospace, Drone & Defence Tech': CorpsVerticalFitTier.limited,
    'Corporate Governance': CorpsVerticalFitTier.strong,
    'Intelligence & Vigilance': CorpsVerticalFitTier.limited,
    'Corporate Investigations': CorpsVerticalFitTier.possible,
    'Brand Protection & IPR': CorpsVerticalFitTier.possible,
  },
};

/// The fit tier for [corpsOrArm] on [verticalName]. Medical and legal
/// verticals resolve deterministically from the same hard-gate lists used
/// to constrain Vertical Fit ranking ([kMedicalCorps]/[kJagCorps]) rather
/// than the editorial table, so this can never contradict the rest of the
/// app's Corps/Arm logic. Falls back to [CorpsVerticalFitTier.limited] for
/// any general-vertical cell the editorial table doesn't cover.
CorpsVerticalFitTier corpsVerticalFitTier(String corpsOrArm, String verticalName) {
  final isMedicalVertical = kMedicalCareerVerticals.any((v) => v.name == verticalName);
  final isLegalVertical = kLegalCareerVerticals.any((v) => v.name == verticalName);

  if (isMedicalVertical) {
    return kMedicalCorps.contains(corpsOrArm) ? CorpsVerticalFitTier.strong : CorpsVerticalFitTier.restricted;
  }
  if (isLegalVertical) {
    return kJagCorps.contains(corpsOrArm) ? CorpsVerticalFitTier.strong : CorpsVerticalFitTier.restricted;
  }
  return kGeneralVerticalFitByCorps[corpsOrArm]?[verticalName] ?? CorpsVerticalFitTier.limited;
}
