// Sourced from the user-provided city master list (108 cities, Tier 1/
// Tier 2 India). Mirrors lib/features/job_matches/india_cities.dart —
// keep both in sync if the source list changes.
export const INDIA_CITIES = [
  { id: 1, city: 'Ahmedabad', stateUt: 'Gujarat', tier: 'tier1', employmentCluster: 'Ahmedabad Metropolitan Region' },
  { id: 2, city: 'Bengaluru', stateUt: 'Karnataka', tier: 'tier1', employmentCluster: 'Bengaluru Metropolitan Region' },
  { id: 3, city: 'Chennai', stateUt: 'Tamil Nadu', tier: 'tier1', employmentCluster: 'Chennai Metropolitan Region' },
  { id: 4, city: 'Delhi', stateUt: 'Delhi', tier: 'tier1', employmentCluster: 'Delhi NCR' },
  { id: 5, city: 'Hyderabad', stateUt: 'Telangana', tier: 'tier1', employmentCluster: 'Hyderabad Metropolitan Region' },
  { id: 6, city: 'Kolkata', stateUt: 'West Bengal', tier: 'tier1', employmentCluster: 'Kolkata Metropolitan Region' },
  { id: 7, city: 'Mumbai', stateUt: 'Maharashtra', tier: 'tier1', employmentCluster: 'Mumbai Metropolitan Region' },
  { id: 8, city: 'Pune', stateUt: 'Maharashtra', tier: 'tier1', employmentCluster: 'Pune Metropolitan Region' },
  { id: 9, city: 'Agra', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Agra Employment Market' },
  { id: 10, city: 'Ajmer', stateUt: 'Rajasthan', tier: 'tier2', employmentCluster: 'Ajmer Employment Market' },
  { id: 11, city: 'Akola', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Akola Employment Market' },
  { id: 12, city: 'Aligarh', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Aligarh Employment Market' },
  { id: 13, city: 'Amravati', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Amravati Employment Market' },
  { id: 14, city: 'Amritsar', stateUt: 'Punjab', tier: 'tier2', employmentCluster: 'Amritsar Employment Market' },
  { id: 15, city: 'Anand', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Anand Employment Market' },
  { id: 16, city: 'Asansol', stateUt: 'West Bengal', tier: 'tier2', employmentCluster: 'Asansol Employment Market' },
  { id: 17, city: 'Aurangabad / Chhatrapati Sambhajinagar', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Aurangabad / Chhatrapati Sambhajinagar Employment Market' },
  { id: 18, city: 'Bareilly', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Bareilly Employment Market' },
  { id: 19, city: 'Bardhaman', stateUt: 'West Bengal', tier: 'tier2', employmentCluster: 'Bardhaman Employment Market' },
  { id: 20, city: 'Belagavi', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Belagavi Employment Market' },
  { id: 21, city: 'Bhavnagar', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Bhavnagar Employment Market' },
  { id: 22, city: 'Bhiwandi', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Mumbai Metropolitan Region' },
  { id: 23, city: 'Bhopal', stateUt: 'Madhya Pradesh', tier: 'tier2', employmentCluster: 'Bhopal Employment Market' },
  { id: 24, city: 'Bhubaneswar', stateUt: 'Odisha', tier: 'tier2', employmentCluster: 'Bhubaneswar Employment Market' },
  { id: 25, city: 'Bikaner', stateUt: 'Rajasthan', tier: 'tier2', employmentCluster: 'Bikaner Employment Market' },
  { id: 26, city: 'Bokaro Steel City', stateUt: 'Jharkhand', tier: 'tier2', employmentCluster: 'Bokaro Steel City Employment Market' },
  { id: 27, city: 'Ballari', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Ballari Employment Market' },
  { id: 28, city: 'Bhilai', stateUt: 'Chhattisgarh', tier: 'tier2', employmentCluster: 'Bhilai Employment Market' },
  { id: 29, city: 'Chandigarh', stateUt: 'Chandigarh', tier: 'tier2', employmentCluster: 'Chandigarh Employment Market' },
  { id: 30, city: 'Coimbatore', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Coimbatore Employment Market' },
  { id: 31, city: 'Cuttack', stateUt: 'Odisha', tier: 'tier2', employmentCluster: 'Cuttack Employment Market' },
  { id: 32, city: 'Dehradun', stateUt: 'Uttarakhand', tier: 'tier2', employmentCluster: 'Dehradun Employment Market' },
  { id: 33, city: 'Dombivli', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Mumbai Metropolitan Region' },
  { id: 34, city: 'Dhanbad', stateUt: 'Jharkhand', tier: 'tier2', employmentCluster: 'Dhanbad Employment Market' },
  { id: 35, city: 'Durgapur', stateUt: 'West Bengal', tier: 'tier2', employmentCluster: 'Durgapur Employment Market' },
  { id: 36, city: 'Erode', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Erode Employment Market' },
  { id: 37, city: 'Faridabad', stateUt: 'Haryana', tier: 'tier2', employmentCluster: 'Delhi NCR' },
  { id: 38, city: 'Ghaziabad', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Delhi NCR' },
  { id: 39, city: 'Gorakhpur', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Gorakhpur Employment Market' },
  { id: 40, city: 'Guntur', stateUt: 'Andhra Pradesh', tier: 'tier2', employmentCluster: 'Guntur Employment Market' },
  { id: 41, city: 'Gurugram', stateUt: 'Haryana', tier: 'tier2', employmentCluster: 'Delhi NCR' },
  { id: 42, city: 'Guwahati', stateUt: 'Assam', tier: 'tier2', employmentCluster: 'Guwahati Employment Market' },
  { id: 43, city: 'Gwalior', stateUt: 'Madhya Pradesh', tier: 'tier2', employmentCluster: 'Gwalior Employment Market' },
  { id: 44, city: 'Hubballi-Dharwad', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Hubballi-Dharwad Employment Market' },
  { id: 45, city: 'Indore', stateUt: 'Madhya Pradesh', tier: 'tier2', employmentCluster: 'Indore Employment Market' },
  { id: 46, city: 'Jabalpur', stateUt: 'Madhya Pradesh', tier: 'tier2', employmentCluster: 'Jabalpur Employment Market' },
  { id: 47, city: 'Jaipur', stateUt: 'Rajasthan', tier: 'tier2', employmentCluster: 'Jaipur Employment Market' },
  { id: 48, city: 'Jalandhar', stateUt: 'Punjab', tier: 'tier2', employmentCluster: 'Jalandhar Employment Market' },
  { id: 49, city: 'Jalgaon', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Jalgaon Employment Market' },
  { id: 50, city: 'Jammu', stateUt: 'Jammu & Kashmir', tier: 'tier2', employmentCluster: 'Jammu Employment Market' },
  { id: 51, city: 'Jamshedpur', stateUt: 'Jharkhand', tier: 'tier2', employmentCluster: 'Jamshedpur Employment Market' },
  { id: 52, city: 'Jamnagar', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Jamnagar Employment Market' },
  { id: 53, city: 'Jhansi', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Jhansi Employment Market' },
  { id: 54, city: 'Jodhpur', stateUt: 'Rajasthan', tier: 'tier2', employmentCluster: 'Jodhpur Employment Market' },
  { id: 55, city: 'Kalaburagi', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Kalaburagi Employment Market' },
  { id: 56, city: 'Kakinada', stateUt: 'Andhra Pradesh', tier: 'tier2', employmentCluster: 'Kakinada Employment Market' },
  { id: 57, city: 'Kannur', stateUt: 'Kerala', tier: 'tier2', employmentCluster: 'Kannur Employment Market' },
  { id: 58, city: 'Kanpur', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Kanpur Employment Market' },
  { id: 59, city: 'Karimnagar', stateUt: 'Telangana', tier: 'tier2', employmentCluster: 'Karimnagar Employment Market' },
  { id: 60, city: 'Karnal', stateUt: 'Haryana', tier: 'tier2', employmentCluster: 'Karnal Employment Market' },
  { id: 61, city: 'Kochi', stateUt: 'Kerala', tier: 'tier2', employmentCluster: 'Kochi Employment Market' },
  { id: 62, city: 'Kolhapur', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Kolhapur Employment Market' },
  { id: 63, city: 'Kollam', stateUt: 'Kerala', tier: 'tier2', employmentCluster: 'Kollam Employment Market' },
  { id: 64, city: 'Kota', stateUt: 'Rajasthan', tier: 'tier2', employmentCluster: 'Kota Employment Market' },
  { id: 65, city: 'Kozhikode', stateUt: 'Kerala', tier: 'tier2', employmentCluster: 'Kozhikode Employment Market' },
  { id: 66, city: 'Kurnool', stateUt: 'Andhra Pradesh', tier: 'tier2', employmentCluster: 'Kurnool Employment Market' },
  { id: 67, city: 'Ludhiana', stateUt: 'Punjab', tier: 'tier2', employmentCluster: 'Ludhiana Employment Market' },
  { id: 68, city: 'Lucknow', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Lucknow Employment Market' },
  { id: 69, city: 'Madurai', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Madurai Employment Market' },
  { id: 70, city: 'Mathura', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Mathura Employment Market' },
  { id: 71, city: 'Mangaluru', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Mangaluru Employment Market' },
  { id: 72, city: 'Meerut', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Meerut Employment Market' },
  { id: 73, city: 'Moradabad', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Moradabad Employment Market' },
  { id: 74, city: 'Mysuru', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Mysuru Employment Market' },
  { id: 75, city: 'Nagpur', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Nagpur Employment Market' },
  { id: 76, city: 'Nanded', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Nanded Employment Market' },
  { id: 77, city: 'Nadiad', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Nadiad Employment Market' },
  { id: 78, city: 'Nashik', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Nashik Employment Market' },
  { id: 79, city: 'Nellore', stateUt: 'Andhra Pradesh', tier: 'tier2', employmentCluster: 'Nellore Employment Market' },
  { id: 80, city: 'Noida', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Delhi NCR' },
  { id: 81, city: 'Patna', stateUt: 'Bihar', tier: 'tier2', employmentCluster: 'Patna Employment Market' },
  { id: 82, city: 'Pimpri-Chinchwad', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Pune Metropolitan Region' },
  { id: 83, city: 'Puducherry', stateUt: 'Puducherry', tier: 'tier2', employmentCluster: 'Puducherry Employment Market' },
  { id: 84, city: 'Prayagraj', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Prayagraj Employment Market' },
  { id: 85, city: 'Raipur', stateUt: 'Chhattisgarh', tier: 'tier2', employmentCluster: 'Raipur Employment Market' },
  { id: 86, city: 'Rajkot', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Rajkot Employment Market' },
  { id: 87, city: 'Ranchi', stateUt: 'Jharkhand', tier: 'tier2', employmentCluster: 'Ranchi Employment Market' },
  { id: 88, city: 'Rourkela', stateUt: 'Odisha', tier: 'tier2', employmentCluster: 'Rourkela Employment Market' },
  { id: 89, city: 'Saharanpur', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Saharanpur Employment Market' },
  { id: 90, city: 'Salem', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Salem Employment Market' },
  { id: 91, city: 'Sangli', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Sangli Employment Market' },
  { id: 92, city: 'Shimla', stateUt: 'Himachal Pradesh', tier: 'tier2', employmentCluster: 'Shimla Employment Market' },
  { id: 93, city: 'Siliguri', stateUt: 'West Bengal', tier: 'tier2', employmentCluster: 'Siliguri Employment Market' },
  { id: 94, city: 'Solapur', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Solapur Employment Market' },
  { id: 95, city: 'Srinagar', stateUt: 'Jammu & Kashmir', tier: 'tier2', employmentCluster: 'Srinagar Employment Market' },
  { id: 96, city: 'Surat', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Surat Employment Market' },
  { id: 97, city: 'Thanjavur', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Thanjavur Employment Market' },
  { id: 98, city: 'Thiruvananthapuram', stateUt: 'Kerala', tier: 'tier2', employmentCluster: 'Thiruvananthapuram Employment Market' },
  { id: 99, city: 'Thrissur', stateUt: 'Kerala', tier: 'tier2', employmentCluster: 'Thrissur Employment Market' },
  { id: 100, city: 'Tiruchirappalli', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Tiruchirappalli Employment Market' },
  { id: 101, city: 'Tirunelveli', stateUt: 'Tamil Nadu', tier: 'tier2', employmentCluster: 'Tirunelveli Employment Market' },
  { id: 102, city: 'Ujjain', stateUt: 'Madhya Pradesh', tier: 'tier2', employmentCluster: 'Ujjain Employment Market' },
  { id: 103, city: 'Vijayapura', stateUt: 'Karnataka', tier: 'tier2', employmentCluster: 'Vijayapura Employment Market' },
  { id: 104, city: 'Vadodara', stateUt: 'Gujarat', tier: 'tier2', employmentCluster: 'Vadodara Employment Market' },
  { id: 105, city: 'Varanasi', stateUt: 'Uttar Pradesh', tier: 'tier2', employmentCluster: 'Varanasi Employment Market' },
  { id: 106, city: 'Vasai-Virar', stateUt: 'Maharashtra', tier: 'tier2', employmentCluster: 'Mumbai Metropolitan Region' },
  { id: 107, city: 'Vijayawada', stateUt: 'Andhra Pradesh', tier: 'tier2', employmentCluster: 'Vijayawada Employment Market' },
  { id: 108, city: 'Visakhapatnam', stateUt: 'Andhra Pradesh', tier: 'tier2', employmentCluster: 'Visakhapatnam Employment Market' },
];
