// Sourced from the user-provided Top 250 India companies list. Mirrors
// lib/features/job_matches/top_companies.dart — keep both in sync.
export const TOP_COMPANIES = [
  { rank: 1, name: 'Tata Consultancy Services (TCS)', industry: 'IT Services' },
  { rank: 2, name: 'Infosys', industry: 'IT Services' },
  { rank: 3, name: 'Wipro', industry: 'IT Services' },
  { rank: 4, name: 'HCLTech', industry: 'IT Services' },
  { rank: 5, name: 'Tech Mahindra', industry: 'IT Services' },
  { rank: 6, name: 'LTIMindtree', industry: 'IT Services' },
  { rank: 7, name: 'Mphasis', industry: 'IT Services' },
  { rank: 8, name: 'Persistent Systems', industry: 'IT Services' },
  { rank: 9, name: 'Coforge', industry: 'IT Services' },
  { rank: 10, name: 'L&T Technology Services', industry: 'IT Services' },
  { rank: 11, name: 'Larsen & Toubro', industry: 'IT Services' },
  { rank: 12, name: 'Cyient', industry: 'IT Services' },
  { rank: 13, name: 'KPIT Technologies', industry: 'IT Services' },
  { rank: 14, name: 'Zensar Technologies', industry: 'IT Services' },
  { rank: 15, name: 'Hexaware Technologies', industry: 'IT Services' },
  { rank: 16, name: 'Mastek', industry: 'IT Services' },
  { rank: 17, name: 'Birlasoft', industry: 'IT Services' },
  { rank: 18, name: 'Tata Elxsi', industry: 'IT Services' },
  { rank: 19, name: 'Sonata Software', industry: 'IT Services' },
  { rank: 20, name: 'Oracle India', industry: 'IT / Software' },
  { rank: 21, name: 'IBM India', industry: 'IT / Software' },
  { rank: 22, name: 'Accenture India', industry: 'IT Services' },
  { rank: 23, name: 'Cognizant India', industry: 'IT Services' },
  { rank: 24, name: 'Capgemini India', industry: 'IT Services' },
  { rank: 25, name: 'DXC Technology India', industry: 'IT Services' },
  { rank: 26, name: 'NTT DATA India', industry: 'IT Services' },
  { rank: 27, name: 'Genpact', industry: 'IT / BPM' },
  { rank: 28, name: 'Concentrix', industry: 'IT / BPM' },
  { rank: 29, name: 'Teleperformance India', industry: 'IT / BPM' },
  { rank: 30, name: 'WNS Global Services', industry: 'IT / BPM' },
  { rank: 31, name: 'Sutherland Global Services', industry: 'IT / BPM' },
  { rank: 32, name: 'Foundever India', industry: 'IT / BPM' },
  { rank: 33, name: 'EXL Service', industry: 'IT / BPM' },
  { rank: 34, name: 'Evalueserve', industry: 'IT / BPM' },
  { rank: 35, name: 'TTEC India', industry: 'IT / BPM' },
  { rank: 36, name: 'State Bank of India (SBI)', industry: 'Banking' },
  { rank: 37, name: 'HDFC Bank', industry: 'Banking' },
  { rank: 38, name: 'ICICI Bank', industry: 'Banking' },
  { rank: 39, name: 'Axis Bank', industry: 'Banking' },
  { rank: 40, name: 'Kotak Mahindra Bank', industry: 'Banking' },
  { rank: 41, name: 'IndusInd Bank', industry: 'Banking' },
  { rank: 42, name: 'Yes Bank', industry: 'Banking' },
  { rank: 43, name: 'IDFC FIRST Bank', industry: 'Banking' },
  { rank: 44, name: 'Federal Bank', industry: 'Banking' },
  { rank: 45, name: 'Bank of Baroda', industry: 'Banking' },
  { rank: 46, name: 'Canara Bank', industry: 'Banking' },
  { rank: 47, name: 'Punjab National Bank', industry: 'Banking' },
  { rank: 48, name: 'Union Bank of India', industry: 'Banking' },
  { rank: 49, name: 'Bank of India', industry: 'Banking' },
  { rank: 50, name: 'Indian Bank', industry: 'Banking' },
  { rank: 51, name: 'Indian Overseas Bank', industry: 'Banking' },
  { rank: 52, name: 'UCO Bank', industry: 'Banking' },
  { rank: 53, name: 'Central Bank of India', industry: 'Banking' },
  { rank: 54, name: 'Bank of Maharashtra', industry: 'Banking' },
  { rank: 55, name: 'South Indian Bank', industry: 'Banking' },
  { rank: 56, name: 'RBL Bank', industry: 'Banking' },
  { rank: 57, name: 'AU Small Finance Bank', industry: 'Banking' },
  { rank: 58, name: 'Ujjivan Small Finance Bank', industry: 'Banking' },
  { rank: 59, name: 'Bajaj Finance', industry: 'NBFC / Financial Services' },
  { rank: 60, name: 'Bajaj Finserv', industry: 'Financial Services' },
  { rank: 61, name: 'Aditya Birla Capital', industry: 'Financial Services' },
  { rank: 62, name: 'Tata Capital', industry: 'Financial Services' },
  { rank: 63, name: 'Shriram Finance', industry: 'NBFC / Financial Services' },
  { rank: 64, name: 'Mahindra Finance', industry: 'NBFC / Financial Services' },
  { rank: 65, name: 'Cholamandalam Investment & Finance', industry: 'NBFC / Financial Services' },
  { rank: 66, name: 'Muthoot Finance', industry: 'NBFC / Financial Services' },
  { rank: 67, name: 'Manappuram Finance', industry: 'NBFC / Financial Services' },
  { rank: 68, name: 'L&T Finance', industry: 'NBFC / Financial Services' },
  { rank: 69, name: 'HDB Financial Services', industry: 'NBFC / Financial Services' },
  { rank: 70, name: 'SBI Life Insurance', industry: 'Insurance' },
  { rank: 71, name: 'LIC of India', industry: 'Insurance' },
  { rank: 72, name: 'HDFC Life', industry: 'Insurance' },
  { rank: 73, name: 'ICICI Prudential Life Insurance', industry: 'Insurance' },
  { rank: 74, name: 'Max Life Insurance', industry: 'Insurance' },
  { rank: 75, name: 'Bajaj Allianz Life Insurance', industry: 'Insurance' },
  { rank: 76, name: 'Tata AIA Life Insurance', industry: 'Insurance' },
  { rank: 77, name: 'Aditya Birla Sun Life Insurance', industry: 'Insurance' },
  { rank: 78, name: 'Star Health and Allied Insurance', industry: 'Insurance' },
  { rank: 79, name: 'New India Assurance', industry: 'Insurance' },
  { rank: 80, name: 'Reliance Industries', industry: 'Diversified / Energy' },
  { rank: 81, name: 'Adani Enterprises', industry: 'Diversified / Infrastructure' },
  { rank: 82, name: 'Adani Ports and SEZ', industry: 'Infrastructure' },
  { rank: 83, name: 'Adani Power', industry: 'Power' },
  { rank: 84, name: 'Adani Green Energy', industry: 'Renewable Energy' },
  { rank: 85, name: 'Larsen & Toubro (L&T)', industry: 'Engineering / Infrastructure' },
  { rank: 86, name: 'Tata Consumer Products', industry: 'Conglomerate' },
  { rank: 87, name: 'Mahindra & Mahindra', industry: 'Automotive / Diversified' },
  { rank: 88, name: 'Bajaj Holdings & Investment', industry: 'Conglomerate' },
  { rank: 89, name: 'Aditya Birla Management Corporation', industry: 'Conglomerate' },
  { rank: 90, name: 'Godrej Industries', industry: 'Conglomerate' },
  { rank: 91, name: 'Vedanta', industry: 'Metals / Mining' },
  { rank: 92, name: 'JSW Group', industry: 'Conglomerate / Infrastructure' },
  { rank: 93, name: 'Jindal Steel & Power', industry: 'Steel / Energy' },
  { rank: 94, name: 'Essar Oil', industry: 'Conglomerate' },
  { rank: 95, name: 'Indian Oil Corporation (IOCL)', industry: 'Oil & Gas' },
  { rank: 96, name: 'Bharat Petroleum (BPCL)', industry: 'Oil & Gas' },
  { rank: 97, name: 'Hindustan Petroleum (HPCL)', industry: 'Oil & Gas' },
  { rank: 98, name: 'Oil and Natural Gas Corporation (ONGC)', industry: 'Oil & Gas' },
  { rank: 99, name: 'GAIL India', industry: 'Oil & Gas' },
  { rank: 100, name: 'Petronet LNG', industry: 'Oil & Gas' },
  { rank: 101, name: 'Nayara Energy', industry: 'Oil & Gas' },
  { rank: 102, name: 'Jio-bp', industry: 'Oil & Gas / Retail' },
  { rank: 103, name: 'NTPC', industry: 'Power' },
  { rank: 104, name: 'Power Grid Corporation of India', industry: 'Power' },
  { rank: 105, name: 'NHPC', industry: 'Power' },
  { rank: 106, name: 'SJVN', industry: 'Power' },
  { rank: 107, name: 'REC Limited', industry: 'Power / Finance' },
  { rank: 108, name: 'Power Finance Corporation (PFC)', industry: 'Power / Finance' },
  { rank: 109, name: 'Tata Power', industry: 'Power' },
  { rank: 110, name: 'JSW Energy', industry: 'Power' },
  { rank: 111, name: 'Torrent Power', industry: 'Power' },
  { rank: 112, name: 'Adani Energy Solutions', industry: 'Power' },
  { rank: 113, name: 'CESC', industry: 'Power' },
  { rank: 114, name: 'Tata Motors', industry: 'Automotive' },
  { rank: 115, name: 'Maruti Suzuki India', industry: 'Automotive' },
  { rank: 116, name: 'Hyundai Motor India', industry: 'Automotive' },
  { rank: 117, name: 'Toyota Kirloskar Motor', industry: 'Automotive' },
  { rank: 118, name: 'Honda Cars India', industry: 'Automotive' },
  { rank: 119, name: 'Kia India', industry: 'Automotive' },
  { rank: 120, name: 'Ashok Leyland', industry: 'Automotive' },
  { rank: 121, name: 'Eicher Motors', industry: 'Automotive' },
  { rank: 122, name: 'TVS Motor Company', industry: 'Automotive' },
  { rank: 123, name: 'Bajaj Auto', industry: 'Automotive' },
  { rank: 124, name: 'Hero MotoCorp', industry: 'Automotive' },
  { rank: 125, name: 'Force Motors', industry: 'Automotive' },
  { rank: 126, name: 'Tata AutoComp Systems', industry: 'Auto Components' },
  { rank: 127, name: 'Motherson', industry: 'Auto Components' },
  { rank: 128, name: 'Bosch India', industry: 'Auto Components' },
  { rank: 129, name: 'ZF India', industry: 'Auto Components' },
  { rank: 130, name: 'Continental India', industry: 'Auto Components' },
  { rank: 131, name: 'Schaeffler India', industry: 'Auto Components' },
  { rank: 132, name: 'Cummins India', industry: 'Engineering' },
  { rank: 133, name: 'Siemens India', industry: 'Engineering' },
  { rank: 134, name: 'ABB India', industry: 'Engineering' },
  { rank: 135, name: 'Honeywell India', industry: 'Engineering / Technology' },
  { rank: 136, name: 'Schneider Electric India', industry: 'Engineering / Energy' },
  { rank: 137, name: 'GE Vernova India', industry: 'Energy Technology' },
  { rank: 138, name: 'Bharat Heavy Electricals (BHEL)', industry: 'Engineering / PSU' },
  { rank: 139, name: 'HAL', industry: 'Aerospace / Defence' },
  { rank: 140, name: 'Bharat Electronics (BEL)', industry: 'Defence Electronics' },
  { rank: 141, name: 'Bharat Dynamics (BDL)', industry: 'Defence' },
  { rank: 142, name: 'Mazagon Dock Shipbuilders', industry: 'Shipbuilding / Defence' },
  { rank: 143, name: 'Cochin Shipyard', industry: 'Shipbuilding / Defence' },
  { rank: 144, name: 'Garden Reach Shipbuilders', industry: 'Shipbuilding / Defence' },
  { rank: 145, name: 'Tata Steel', industry: 'Steel' },
  { rank: 146, name: 'JSW Steel', industry: 'Steel' },
  { rank: 147, name: 'SAIL', industry: 'Steel / PSU' },
  { rank: 148, name: 'Hindalco Industries', industry: 'Metals' },
  { rank: 149, name: 'Vedanta Aluminium', industry: 'Metals' },
  { rank: 150, name: 'Jindal Stainless', industry: 'Steel' },
  { rank: 151, name: 'UltraTech Cement', industry: 'Cement' },
  { rank: 152, name: 'ACC Limited', industry: 'Cement' },
  { rank: 153, name: 'Ambuja Cements', industry: 'Cement' },
  { rank: 154, name: 'Shree Cement', industry: 'Cement' },
  { rank: 155, name: 'Dalmia Bharat', industry: 'Cement' },
  { rank: 156, name: 'Grasim Industries', industry: 'Diversified / Cement' },
  { rank: 157, name: 'Pidilite Industries', industry: 'Chemicals' },
  { rank: 158, name: 'Asian Paints', industry: 'Paints / Chemicals' },
  { rank: 159, name: 'Berger Paints', industry: 'Paints / Chemicals' },
  { rank: 160, name: 'UPL', industry: 'Agrochemicals' },
  { rank: 161, name: 'Deepak Fertilisers', industry: 'Chemicals / Fertilisers' },
  { rank: 162, name: 'Tata Chemicals', industry: 'Chemicals' },
  { rank: 163, name: 'Aarti Industries', industry: 'Chemicals' },
  { rank: 164, name: 'SRF Limited', industry: 'Chemicals' },
  { rank: 165, name: 'Hindustan Unilever (HUL)', industry: 'FMCG' },
  { rank: 166, name: 'ITC', industry: 'FMCG / Diversified' },
  { rank: 167, name: 'Nestlé India', industry: 'FMCG' },
  { rank: 168, name: 'Britannia Industries', industry: 'FMCG' },
  { rank: 169, name: 'Dabur India', industry: 'FMCG' },
  { rank: 170, name: 'Marico', industry: 'FMCG' },
  { rank: 171, name: 'Godrej Consumer Products', industry: 'FMCG' },
  { rank: 172, name: 'Procter & Gamble India', industry: 'FMCG' },
  { rank: 173, name: 'Colgate-Palmolive India', industry: 'FMCG' },
  { rank: 174, name: 'Reckitt India', industry: 'FMCG' },
  { rank: 175, name: 'Emami', industry: 'FMCG' },
  { rank: 176, name: 'Jyothy Labs', industry: 'FMCG' },
  { rank: 177, name: 'Varun Beverages', industry: 'FMCG' },
  { rank: 178, name: 'United Breweries', industry: 'FMCG / Beverages' },
  { rank: 179, name: 'Sun Pharmaceutical Industries', industry: 'Pharmaceuticals' },
  { rank: 180, name: 'Dr. Reddy\'s Laboratories', industry: 'Pharmaceuticals' },
  { rank: 181, name: 'Cipla', industry: 'Pharmaceuticals' },
  { rank: 182, name: 'Lupin', industry: 'Pharmaceuticals' },
  { rank: 183, name: 'Aurobindo Pharma', industry: 'Pharmaceuticals' },
  { rank: 184, name: 'Zydus Lifesciences', industry: 'Pharmaceuticals' },
  { rank: 185, name: 'Torrent Pharmaceuticals', industry: 'Pharmaceuticals' },
  { rank: 186, name: 'Mankind Pharma', industry: 'Pharmaceuticals' },
  { rank: 187, name: 'Alkem Laboratories', industry: 'Pharmaceuticals' },
  { rank: 188, name: 'Glenmark Pharmaceuticals', industry: 'Pharmaceuticals' },
  { rank: 189, name: 'Abbott India', industry: 'Pharmaceuticals' },
  { rank: 190, name: 'Biocon', industry: 'Biopharma' },
  { rank: 191, name: 'Divi\'s Laboratories', industry: 'Pharmaceuticals' },
  { rank: 192, name: 'Apollo Hospitals', industry: 'Healthcare' },
  { rank: 193, name: 'Fortis Healthcare', industry: 'Healthcare' },
  { rank: 194, name: 'Max Healthcare', industry: 'Healthcare' },
  { rank: 195, name: 'Manipal Hospitals', industry: 'Healthcare' },
  { rank: 196, name: 'Narayana Health', industry: 'Healthcare' },
  { rank: 197, name: 'Medanta', industry: 'Healthcare' },
  { rank: 198, name: 'Metropolis Healthcare', industry: 'Diagnostics' },
  { rank: 199, name: 'Dr Lal PathLabs', industry: 'Diagnostics' },
  { rank: 200, name: 'Reliance Retail', industry: 'Retail' },
  { rank: 201, name: 'DMart / Avenue Supermarts', industry: 'Retail' },
  { rank: 202, name: 'Trent', industry: 'Retail' },
  { rank: 203, name: 'Shoppers Stop', industry: 'Retail' },
  { rank: 204, name: 'Aditya Birla Fashion & Retail', industry: 'Retail' },
  { rank: 205, name: 'Lifestyle International', industry: 'Retail' },
  { rank: 206, name: 'Flipkart', industry: 'E-commerce' },
  { rank: 207, name: 'Amazon India', industry: 'E-commerce' },
  { rank: 208, name: 'Myntra', industry: 'E-commerce' },
  { rank: 209, name: 'Meesho', industry: 'E-commerce' },
  { rank: 210, name: 'Nykaa', industry: 'E-commerce / Beauty' },
  { rank: 211, name: 'Swiggy', industry: 'Food Tech / Delivery' },
  { rank: 212, name: 'Zomato', industry: 'Food Tech / Delivery' },
  { rank: 213, name: 'Zepto', industry: 'Quick Commerce' },
  { rank: 214, name: 'Blinkit', industry: 'Quick Commerce' },
  { rank: 215, name: 'Bharti Airtel', industry: 'Telecom' },
  { rank: 216, name: 'Reliance Jio', industry: 'Telecom / Digital' },
  { rank: 217, name: 'Vodafone Idea', industry: 'Telecom' },
  { rank: 218, name: 'Tata Communications', industry: 'Telecom / Digital' },
  { rank: 219, name: 'Network18', industry: 'Media' },
  { rank: 220, name: 'Disney Star India', industry: 'Media' },
  { rank: 221, name: 'Sony Pictures Networks India', industry: 'Media' },
  { rank: 222, name: 'Zee Entertainment Enterprises', industry: 'Media' },
  { rank: 223, name: 'Indian Railways', industry: 'Rail / Transport' },
  { rank: 224, name: 'Air India', industry: 'Aviation' },
  { rank: 225, name: 'IndiGo', industry: 'Aviation' },
  { rank: 226, name: 'Akasa Air', industry: 'Aviation' },
  { rank: 227, name: 'MakeMyTrip', industry: 'Travel Tech' },
  { rank: 228, name: 'Thomas Cook India', industry: 'Travel' },
  { rank: 229, name: 'Blue Dart', industry: 'Logistics' },
  { rank: 230, name: 'Delhivery', industry: 'Logistics' },
  { rank: 231, name: 'Ecom Express', industry: 'Logistics' },
  { rank: 232, name: 'DHL Express India', industry: 'Logistics' },
  { rank: 233, name: 'FedEx India', industry: 'Logistics' },
  { rank: 234, name: 'Mahindra Logistics', industry: 'Logistics' },
  { rank: 235, name: 'TCI - Transport Corporation of India', industry: 'Logistics' },
  { rank: 236, name: 'Oberoi Group', industry: 'Hospitality' },
  { rank: 237, name: 'ITC Hotels', industry: 'Hospitality' },
  { rank: 238, name: 'Indian Hotels Company (IHCL)', industry: 'Hospitality' },
  { rank: 239, name: 'Marriott International India', industry: 'Hospitality' },
  { rank: 240, name: 'Hilton India', industry: 'Hospitality' },
  { rank: 241, name: 'Deloitte India', industry: 'Professional Services' },
  { rank: 242, name: 'PwC India', industry: 'Professional Services' },
  { rank: 243, name: 'EY India', industry: 'Professional Services' },
  { rank: 244, name: 'KPMG India', industry: 'Professional Services' },
  { rank: 245, name: 'Grant Thornton Bharat', industry: 'Professional Services' },
  { rank: 246, name: 'CBRE India', industry: 'Real Estate Services' },
  { rank: 247, name: 'JLL India', industry: 'Real Estate Services' },
  { rank: 248, name: 'SBI General Insurance', industry: 'Insurance' },
  { rank: 249, name: 'ICICI Lombard General Insurance', industry: 'Insurance' },
  { rank: 250, name: 'Bajaj Allianz General Insurance', industry: 'Insurance' },
];
