import 'ai_competency.dart';

/// The officer's self-rated familiarity (1-5) for each of the five AI
/// dimensions, collected via a short quiz. The readiness score is computed
/// deterministically from these ratings — never left to the LLM to invent.
class AiSelfAssessment {
  const AiSelfAssessment({required this.ratings});

  /// One 1-5 rating per [AiDimension]. All five dimensions must be present.
  final Map<AiDimension, int> ratings;

  /// Readiness score out of 100, derived directly from the ratings (sum of
  /// five 1-5 ratings, out of a max of 25, scaled to 100).
  int get readinessScore {
    final sum = ratings.values.fold<int>(0, (total, r) => total + r);
    return ((sum / 25) * 100).round();
  }

  /// Per-dimension score out of 100 (rating scaled from 1-5 to 20-100).
  Map<AiDimension, int> get dimensionScores =>
      ratings.map((dimension, rating) => MapEntry(dimension, rating * 20));
}

enum GapSeverity { high, medium, low }

extension GapSeverityLabel on GapSeverity {
  String get label => switch (this) {
        GapSeverity.high => 'High priority',
        GapSeverity.medium => 'Medium priority',
        GapSeverity.low => 'Low priority',
      };
}

/// A gap between the officer's current AI competency and what their target
/// roles need, always anchored to a fixed [AiCompetency] — never an invented
/// skill name.
class SkillGap {
  const SkillGap({
    required this.competency,
    required this.severity,
    required this.reason,
  });

  final AiCompetency competency;
  final GapSeverity severity;
  final String reason;
}

enum RoadmapPhase { day30, day60, day90 }

extension RoadmapPhaseLabel on RoadmapPhase {
  String get label => switch (this) {
        RoadmapPhase.day30 => 'First 30 days',
        RoadmapPhase.day60 => 'Days 31-60',
        RoadmapPhase.day90 => 'Days 61-90',
      };
}

/// A single roadmap milestone. Where it recommends a course, [courseId]
/// matches an entry in [kAiCourses] — never a fabricated course.
class RoadmapItem {
  const RoadmapItem({
    required this.phase,
    required this.title,
    required this.description,
    this.courseId,
  });

  final RoadmapPhase phase;
  final String title;
  final String description;
  final String? courseId;
}

/// Result of analysing an officer's CV and self-assessment for AI readiness.
class AiReadinessResult {
  const AiReadinessResult({
    required this.readinessScore,
    required this.scoreRationale,
    required this.dimensionScores,
    required this.skillGaps,
    required this.cvAiBridge,
    required this.roadmap,
  });

  /// 0-100, echoed from [AiSelfAssessment.readinessScore] — computed
  /// deterministically client-side, never generated by the LLM.
  final int readinessScore;
  final String scoreRationale;
  final Map<AiDimension, int> dimensionScores;
  final List<SkillGap> skillGaps;

  /// How the officer's actual CV experience already connects to AI-relevant
  /// capabilities (e.g. data-driven decision-making, process automation) —
  /// grounded only in what the CV actually says.
  final String cvAiBridge;
  final List<RoadmapItem> roadmap;
}
