import 'ai_competency.dart';
import 'ai_readiness_scenario.dart';

/// The officer's answers to the scenario-based readiness quiz — one
/// selected option index per [ScenarioQuestion.id]. Scored deterministically
/// against the fixed answer key in [kAiReadinessQuestions] — never left to
/// the LLM to invent or grade.
class AiScenarioAssessment {
  const AiScenarioAssessment({required this.answers});

  /// questionId -> selected option index.
  final Map<String, int> answers;

  bool _isCorrect(ScenarioQuestion q) => answers[q.id] == q.correctIndex;

  /// Per-tier score out of 100 — percentage of that tier's questions
  /// answered correctly.
  Map<AiReadinessTier, int> get tierScores {
    final scores = <AiReadinessTier, int>{};
    for (final tier in AiReadinessTier.values) {
      final questions = kAiReadinessQuestions.where((q) => q.tier == tier).toList();
      final correct = questions.where(_isCorrect).length;
      scores[tier] = questions.isEmpty ? 0 : ((correct / questions.length) * 100).round();
    }
    return scores;
  }

  /// Overall readiness score out of 100 — the four tier scores, equally
  /// weighted. Equal weighting is an explicit, visible product choice (not
  /// asserted as scientifically derived) until real outcome data exists to
  /// justify a different split.
  int get readinessScore {
    final scores = tierScores.values;
    if (scores.isEmpty) return 0;
    return (scores.reduce((a, b) => a + b) / scores.length).round();
  }
}

enum GapSeverity { high, medium, low }

extension GapSeverityLabel on GapSeverity {
  String get label => switch (this) {
        GapSeverity.high => 'High priority',
        GapSeverity.medium => 'Medium priority',
        GapSeverity.low => 'Low priority',
      };
}

/// A gap between the officer's current AI competency and what their target
/// roles need, always anchored to a fixed [AiCompetency] — never an invented
/// skill name.
class SkillGap {
  const SkillGap({
    required this.competency,
    required this.severity,
    required this.reason,
  });

  final AiCompetency competency;
  final GapSeverity severity;
  final String reason;

  Map<String, dynamic> toJson() => {
        'competencyId': competency.id,
        'severity': severity.name,
        'reason': reason,
      };

  factory SkillGap.fromJson(Map<String, dynamic> json) => SkillGap(
        competency: kAiCompetencies.firstWhere((c) => c.id == json['competencyId']),
        severity: GapSeverity.values.byName(json['severity'] as String),
        reason: json['reason'] as String,
      );
}

enum RoadmapPhase { day30, day60, day90 }

extension RoadmapPhaseLabel on RoadmapPhase {
  String get label => switch (this) {
        RoadmapPhase.day30 => 'First 30 days',
        RoadmapPhase.day60 => 'Days 31-60',
        RoadmapPhase.day90 => 'Days 61-90',
      };
}

/// A single roadmap milestone. Where it recommends a course, [courseId]
/// matches an entry in [kAiCourses] — never a fabricated course.
class RoadmapItem {
  const RoadmapItem({
    required this.phase,
    required this.title,
    required this.description,
    this.courseId,
  });

  final RoadmapPhase phase;
  final String title;
  final String description;
  final String? courseId;

  Map<String, dynamic> toJson() => {
        'phase': phase.name,
        'title': title,
        'description': description,
        'courseId': courseId,
      };

  factory RoadmapItem.fromJson(Map<String, dynamic> json) => RoadmapItem(
        phase: RoadmapPhase.values.byName(json['phase'] as String),
        title: json['title'] as String,
        description: json['description'] as String,
        courseId: json['courseId'] as String?,
      );
}

/// Result of analysing an officer's CV and scenario-quiz answers for AI
/// readiness.
class AiReadinessResult {
  const AiReadinessResult({
    required this.readinessScore,
    required this.scoreRationale,
    required this.tierScores,
    required this.skillGaps,
    required this.cvAiBridge,
    required this.roadmap,
  });

  /// 0-100, echoed from [AiScenarioAssessment.readinessScore] — computed
  /// deterministically client-side, never generated by the LLM.
  final int readinessScore;
  final String scoreRationale;
  final Map<AiReadinessTier, int> tierScores;
  final List<SkillGap> skillGaps;

  /// How the officer's actual CV experience already connects to AI-relevant
  /// capabilities (e.g. data-driven decision-making, process automation) —
  /// grounded only in what the CV actually says.
  final String cvAiBridge;
  final List<RoadmapItem> roadmap;

  Map<String, dynamic> toJson() => {
        'readinessScore': readinessScore,
        'scoreRationale': scoreRationale,
        'tierScores': tierScores.map((k, v) => MapEntry(k.name, v)),
        'skillGaps': skillGaps.map((g) => g.toJson()).toList(),
        'cvAiBridge': cvAiBridge,
        'roadmap': roadmap.map((r) => r.toJson()).toList(),
      };

  factory AiReadinessResult.fromJson(Map<String, dynamic> json) => AiReadinessResult(
        readinessScore: json['readinessScore'] as int,
        scoreRationale: json['scoreRationale'] as String,
        tierScores: (json['tierScores'] as Map<String, dynamic>).map(
          (k, v) => MapEntry(AiReadinessTier.values.byName(k), v as int),
        ),
        skillGaps: (json['skillGaps'] as List)
            .map((e) => SkillGap.fromJson(e as Map<String, dynamic>))
            .toList(),
        cvAiBridge: json['cvAiBridge'] as String,
        roadmap: (json['roadmap'] as List)
            .map((e) => RoadmapItem.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}
