import 'career_handbook_entry.dart';

/// One combined narrative entry per browsable vertical (see
/// `kAllBrowsableVerticals` in `corps_affinity.dart`) — verticalName must
/// match a real `CareerVertical.name` exactly for every entry. Combines two
/// independently AI-drafted handbook documents: certifications and job
/// titles are never restated here (they come only from `career_vertical.dart`)
/// — this file is narrative context only, reviewed for fabrication before use.
const List<CareerHandbookEntry> kCareerHandbookEntries = [
  CareerHandbookEntry(
    verticalName: 'Operations & Process Excellence',
    whatItDoes: 'Operations keeps a company\'s core product or service moving reliably from one step to the next — the shop floor, a fulfillment hub, a back-office processing centre — while controlling quality, cost and waste. It sets operating standards, tracks throughput and resource use, and fixes recurring problems before they become customer-facing failures. This matters because even a strong product can lose money or customers if day-to-day execution is slow, inconsistent or wasteful.',
    careerRoadmap: 'An officer typically starts by running a single defined operation or process, watching output, quality, manpower and cost directly. Responsibility then widens to multiple teams, shifts or a larger facility with cross-location performance comparisons and improvement projects, then to a major operating area or business unit where the focus shifts to setting standards and managing other managers. At the top of the ladder the scope becomes enterprise-wide, connecting operating performance to strategy, resource allocation and long-term resilience.',
    whoSucceeds: [
      'Execution-biased, resilient leaders who are comfortable in high-tempo, metrics-driven environments',
      'Combat arms and logistics officers tend to transition especially well, given their comfort commanding large teams under pressure',
      'People who can balance empathy for a frontline workforce with a hard focus on numbers',
      'A preference for measurable results and process discipline',
    ],
    whoStruggles: [
      'Dislike of daily firefighting or a preference for slow-paced strategic thinking over immediate action',
      'Discomfort with spreadsheet-based data analysis and close attention to operating detail',
      'Needing formal command authority rather than influence to get things done',
    ],
    whatYoudNeed: 'Any graduate degree is generally acceptable, though technical or operations-related education helps. Six Sigma Green/Black Belt and PMP are the recognised bridge certifications — the former for process-improvement credibility, the latter for structured delivery. A CV should quantify the scale of teams, budgets or multi-site activity managed and any measurable efficiency gains, since no professional licence is normally required but civilian employers need proof that military command experience converts into operating results.',
  ),
  CareerHandbookEntry(
    verticalName: 'Supply Chain & Procurement',
    whatItDoes: 'This function makes sure a company has the materials, equipment and services it needs, when it needs them, at an acceptable cost — spanning sourcing, procurement, warehousing and logistics. It protects margins by keeping inventory lean and sourcing costs controlled, while preventing the production delays and stockouts that come from weak supplier management. The work is as much about negotiation and risk management as it is about tracking shipments.',
    careerRoadmap: 'The typical path starts with running a defined node of the chain — a regional warehouse or a specific procurement category — before moving to coordinating multiple vendors, categories or sites and negotiating within set limits. Later tiers own a major supply-chain area end-to-end, including supplier strategy and continuity risk, before scaling to regional or enterprise-wide network design and, at the top, shaping working capital, resilience and supplier strategy across the whole organisation.',
    whoSucceeds: [
      'Highly analytical, negotiation-savvy officers who are comfortable working with numbers and multiple stakeholders',
      'Army Ordnance Corps, Army Service Corps, Navy Logistics and Air Force Logistics officers transition exceptionally well here',
      'Comfort squeezing value out of large contracts and anticipating cascading effects of delays',
      'Willingness to translate military logistics experience into commercial, supplier-facing terms',
    ],
    whoStruggles: [
      'Discomfort with intense or adversarial negotiation',
      'A preference for leading people directly over managing data streams and vendor relationships',
      'Dislike of detailed tracking and the constant trade-off between cost, speed and resilience',
    ],
    whatYoudNeed: 'Any graduate degree can work, though engineering, business or supply-chain education is helpful. CSCP (APICS) and CPSM are the certifications that carry the most weight, proving familiarity with modern commercial supply-chain frameworks. A CV should highlight the financial value of inventory or assets managed and the scale of the logistics networks controlled; there is no universal professional licence required, but demonstrated commercial thinking matters more than military logistics terminology alone.',
  ),
  CareerHandbookEntry(
    verticalName: 'Security, Risk & Crisis Management',
    whatItDoes: 'This function protects a company\'s people, facilities, information and operational continuity from threats ranging from theft and violence to fraud and natural disasters. It combines prevention, preparedness, incident response and recovery, connecting directly to the business by preventing financial loss and helping the company survive disruption with minimal downtime. Done well, it enables the business to operate rather than locking it down.',
    careerRoadmap: 'Officers typically begin running security arrangements for a single site or defined operation — guards, access control, incident response, local risk assessment — then move to coordinating security across several sites or a region, setting standards and handling more complex incidents. Later tiers own the corporate security programme, threat assessments and crisis plans for an entire business, then integrate physical security with crisis management and enterprise resilience at the executive level, ultimately advising senior leadership on the organisation\'s overall security posture.',
    whoSucceeds: [
      'Calm, observant officers who can assess threats without overreacting and communicate clearly under pressure',
      'Combat arms, Provost and Intelligence officers are a natural fit, though the field is not limited to a particular arm or service',
      'People who understand security as a service function that must enable the business rather than obstruct it',
      'Comfort building relationships with local law enforcement and external stakeholders',
    ],
    whoStruggles: [
      'A rigid \'fortress\' mentality that resists balancing security against business needs',
      'Difficulty justifying return on investment for security spend',
      'Preference for predictable desk work over incident response and stakeholder negotiation',
    ],
    whatYoudNeed: 'Any graduate degree is generally acceptable. CPP (ASIS) is the certification most likely to be recognised, alongside NEBOSH for safety and Business Continuity Institute (BCI) certification for continuity planning. A CV should showcase the complexity of security operations managed, specific incidents mitigated, and experience with modern electronic security systems; being able to demonstrate a clean background and physical fitness is often expected, though requirements vary by industry.',
  ),
  CareerHandbookEntry(
    verticalName: 'Integrated Facilities Management',
    whatItDoes: 'This function keeps corporate real estate — offices, campuses, labs — functioning so employees can work safely and productively. It covers real estate leasing and space planning, maintenance, housekeeping, cafeteria services and workplace safety, and manages a significant share of operating expenditure. Beyond upkeep, it directly affects employee productivity, retention and corporate culture.',
    careerRoadmap: 'The path usually starts with running the day-to-day operations of a single building or small campus — vendors, maintenance, safety — before expanding to larger campuses or multiple regional offices with bigger contracts and space-utilisation tracking. Mid-career tiers own workplace and property strategy across a portfolio, negotiating leases and major fit-out projects, before scaling to enterprise-wide real estate and infrastructure strategy and, ultimately, aligning the company\'s physical footprint with its long-term strategic vision.',
    whoSucceeds: [
      'Service-oriented, highly organised and financially literate officers',
      'Engineers (particularly Civil or Electrical), Quartermasters, and those with extensive Cantonment Board or Station HQ experience are strong fits',
      'A hospitality mindset paired with engineering common sense',
      'Comfort managing contractors, budgets and competing user demands',
    ],
    whoStruggles: [
      'Viewing administrative support roles as beneath the role',
      'Impatience with daily user complaints or vendor management',
      'Preference for work that is visible rather than judged by whether problems quietly disappear',
    ],
    whatYoudNeed: 'An engineering degree or general graduation is generally acceptable. IFMA CFM and RICS are the listed bridge certifications, useful for establishing civilian credibility in facilities and property. A CV should highlight the square footage, budgets or service contracts managed and familiarity with health, safety and environment standards; formal registration is not usually a hard prerequisite for management roles, though some technical work may require licensed specialists.',
  ),
  CareerHandbookEntry(
    verticalName: 'Aviation, Maritime & Fleet Management',
    whatItDoes: 'This vertical manages a company\'s large moving assets — an airline\'s flight and ground operations, a shipping line\'s port operations, or a national vehicle fleet. It exists to maximise the utilisation of expensive, time-sensitive assets while meeting strict safety and regulatory standards, since delays or incidents quickly affect customers, revenue and reputation.',
    careerRoadmap: 'Officers typically start by running the daily turnaround of assets at a specific hub — dispatch, loading, scheduling and maintenance. They then move to overseeing multiple hubs or a larger fleet, handling disruptions and liaising with regulators, before directing operations for a major division with accountability for efficiency and safety-incident outcomes. At the senior tiers the role shifts to setting network strategy, fleet investment decisions and, ultimately, global asset and logistics strategy.',
    whoSucceeds: [
      'Process-obsessed, safety-first leaders who grasp the financial cost of asset downtime',
      'Air Force pilots and ground-duty officers, Navy executive-branch officers and Army Service Corps officers are direct fits',
      'Comfort operating in heavily unionised, tightly regulated environments',
      'Sector-specific domain background, since this vertical is usually not accessible without one',
    ],
    whoStruggles: [
      'Difficulty working within strict regulatory frameworks',
      'No prior exposure to complex rostering or asset-yield thinking',
      'Wanting a fast-changing environment rather than one governed by fixed procedure',
    ],
    whatYoudNeed: 'Specific domain experience is usually expected — aviation operations roles, for example, generally require an aviation background. IATA Airport Operations certification and Certificate in Maritime Operations are the bridge tools most useful for translating military experience into commercial terms. A CV should highlight the scale of fleets or hubs managed and safety outcomes; some regulated technical or command positions may require specific operating licences that should not be assumed from military experience alone.',
  ),
  CareerHandbookEntry(
    verticalName: 'BFSI & Financial Crime Risk',
    whatItDoes: 'Within banking, financial services and insurance, this function prevents the institution from being used for money laundering, terrorism financing or fraud, protecting it from regulatory penalties and reputational damage. The work is evidence-heavy — reviewing transactions and customers, setting controls, investigating alerts and escalating significant risk — while trying not to slow down legitimate customer onboarding.',
    careerRoadmap: 'The typical progression begins with managing analysts who conduct customer checks and investigate transaction alerts against strict accuracy and turnaround targets. It moves to running larger teams handling more complex cases and regulatory reporting, then to owning a major financial-crime operation and its control framework, including facing regulators during audits. At the top tiers, financial-crime risk is integrated into a broader enterprise risk view, culminating in ultimate accountability for the organisation\'s overall risk framework.',
    whoSucceeds: [
      'Detail-obsessed, highly analytical, process-driven officers',
      'Intelligence officers, financial specialists and Provost officers with investigation backgrounds tend to fit well',
      'Comfort digesting complex regulatory text and turning it into operational workflows',
      'Patience for documentation and repetitive case review',
    ],
    whoStruggles: [
      'Dislike of desk-bound data analysis or repetitive compliance work',
      'Preference for physical action over digital investigation',
      'Discomfort making decisions that must be justified from evidence rather than instinct',
    ],
    whatYoudNeed: 'Any graduate degree can be a starting point, though finance or accounting knowledge helps. CAMS is close to a hard prerequisite for being taken seriously in financial-crime work, with FRM more relevant as the role broadens into wider financial risk. A CV should demonstrate management of analytical teams, understanding of risk typologies, and experience with strict compliance frameworks; regulatory permissions vary by role and there is no single universal licence for this path.',
  ),
  CareerHandbookEntry(
    verticalName: 'Intelligence & Vigilance',
    whatItDoes: 'This vertical acts as a company\'s internal early-warning and integrity function, looking for misconduct, conflicts of interest, corruption and other threats to organisational integrity, alongside gathering external information on competitors and market risks. It protects the company\'s integrity and gives decision-makers an information advantage, working through careful, fair fact-finding rather than confrontation.',
    careerRoadmap: 'Officers typically begin by executing background checks and investigating lower-level complaints while maintaining day-to-day information-gathering networks. The role then grows to managing more complex investigations involving middle management and identifying systemic vulnerabilities, before overseeing the entire vigilance and intelligence apparatus, including highly sensitive investigations involving senior executives. At the top tier, the officer holds independent, board-facing accountability for the organisation\'s overall integrity and vigilance framework.',
    whoSucceeds: [
      'Discreet, highly ethical officers with a healthy dose of professional scepticism',
      'Military Intelligence, Provost and officers with deep investigative or specialised operational backgrounds tend to thrive',
      'Comfort operating in the grey areas of corporate politics while maintaining personal integrity',
      'Ability to write meticulous, legal-grade reports',
    ],
    whoStruggles: [
      'Lack of tact or discomfort with confidentiality',
      'Difficulty with the isolation that can come from investigating colleagues',
      'Situations where personal relationships must not influence judgement',
    ],
    whatYoudNeed: 'Any graduate degree is generally acceptable. Certified Fraud Examiner (CFE) is a key bridge certification for understanding commercial fraud typologies, alongside a Certificate in Corporate Vigilance. A CV should highlight experience managing sensitive information networks, conducting interviews, and presenting intelligence briefs to senior leadership; credibility here depends heavily on demonstrating impartial, evidence-based casework.',
  ),
  CareerHandbookEntry(
    verticalName: 'Corporate Investigations',
    whatItDoes: 'When something goes wrong — embezzlement, harassment, data theft, vendor kickbacks — this function establishes exactly what happened and preserves the evidence needed for defensible legal or disciplinary action. Unlike broader vigilance work, it is a reactive, highly specialised function built on interviews, record analysis and evidence handling that can end up in court or before regulators.',
    careerRoadmap: 'The typical path starts with conducting witness interviews, analysing records for anomalies and drafting investigation reports on routine cases. It progresses to leading complex, multi-disciplinary investigations and coordinating with digital forensics and external agencies, then to owning the entire investigations docket for a region or company, including managing the legal risk of investigations themselves. At the senior tiers, the role builds enterprise forensic capability and, ultimately, provides assurance directly to the board on the most serious cases.',
    whoSucceeds: [
      'Skeptical, detail-oriented and highly articulate officers comfortable with confrontation',
      'Military Police, Intelligence and JAG officers tend to be strong fits, since legal training bridges naturally into evidentiary procedure',
      'A strong stomach for dealing with emotional or deceptive subjects while remaining objective',
      'Patience for meticulous documentation and lengthy evidence review',
    ],
    whoStruggles: [
      'Being trusting to a fault',
      'Difficulty with meticulous, sustained documentation',
      'Impatience with sifting through large volumes of records to find a single piece of evidence',
    ],
    whatYoudNeed: 'Any graduate degree works, though a background in law or accounting is an advantage. Certified Fraud Examiner (CFE) is close to essential, supported by a Certified Forensic Investigation Professional credential. A CV should demonstrate a track record of closing complex cases, understanding of the laws of evidence, and the ability to run discreet, high-stakes investigations.',
  ),
  CareerHandbookEntry(
    verticalName: 'Brand Protection & IPR',
    whatItDoes: 'This vertical hunts down counterfeiters, trademark infringers and parallel importers who steal a company\'s intellectual property. It protects revenue and brand reputation by getting fake or unauthorised products — which can be unsafe or poor quality — off the market, both physically and online, often working with law enforcement and customs authorities.',
    careerRoadmap: 'Officers typically start by handling reported infringements directly — monitoring for fake listings, coordinating market sweeps and enforcement raids. The role then grows to mapping entire illicit supply chains and managing investigations into clandestine manufacturing, before owning regional enforcement strategy, external law-firm relationships and prioritisation of the highest-value threats. At the top tiers, the officer aligns IP protection with overall business strategy and coordinates worldwide enforcement efforts to protect the company\'s most valuable intangible assets.',
    whoSucceeds: [
      'Tenacious, legally minded, street-smart operators',
      'Officers with counter-insurgency, intelligence-networking or complex logistics-tracking experience do well, since hunting counterfeiters mirrors mapping illicit networks',
      'Comfort working closely with law enforcement and external agencies',
      'A working grasp of basic trademark and IP concepts',
    ],
    whoStruggles: [
      'Wanting a purely desk-bound role',
      'Reluctance to work closely with law enforcement',
      'Difficulty grasping legal and commercial complexity in enforcement decisions',
    ],
    whatYoudNeed: 'Any graduate degree works, and a law degree is a considerable bonus. Certified Fraud Examiner (CFE) and a foundational IP/Brand Protection fundamentals certificate are useful bridges. A CV should show the ability to manage external agencies, conduct network analysis to trace a problem to its source, and run operations alongside local authorities.',
  ),
  CareerHandbookEntry(
    verticalName: 'Project & Program Management (PMO)',
    whatItDoes: 'The Project Management Office ensures a company\'s strategic initiatives actually get executed — building a new factory, launching a new IT system, integrating an acquisition. While operations runs the daily business, the PMO manages unique, temporary endeavours, keeping complex projects on time, on budget and within scope as connective tissue between corporate silos.',
    careerRoadmap: 'The path typically starts with managing a specific project with defined boundaries — schedules, status tracking, escalations. It grows to managing a \'programme\' of related projects, handling dependencies and resourcing conflicts between teams, then to running project delivery for the whole organisation, setting methodology and giving leadership visibility into progress and risk. At the top tiers, the role manages an enterprise-wide portfolio of investment and, ultimately, leads major organisational transformation.',
    whoSucceeds: [
      'Highly structured, diplomatic and relentless drivers of outcomes',
      'Officers who have managed complex acquisitions, large deployments or multi-agency exercises tend to excel',
      'Comfort leading through influence rather than direct command authority',
      'Tolerance for meticulous documentation and constant negotiation',
    ],
    whoStruggles: [
      'A need for direct command authority to get things done',
      'Dislike of meticulous documentation',
      'Difficulty coordinating many stakeholders who do not report to you',
    ],
    whatYoudNeed: 'Any graduate degree is generally acceptable. PMP is the most widely recognised bridge certification for project delivery, with PRINCE2 and Certified Scrum Master also relevant depending on methodology. A CV should quantify the budgets, timelines and cross-functional teams managed to deliver specific, defined outcomes.',
  ),
  CareerHandbookEntry(
    verticalName: 'Strategy, Consulting & Chief of Staff',
    whatItDoes: 'This vertical acts as the analytical brain trust for senior leadership, examining market trends, competitor moves and internal capability to help decide where the company should go next, and then helping ensure those priorities are actually executed. It matters because leadership time is scarce and poor strategic choices can be very costly.',
    careerRoadmap: 'Officers typically start as the analytical workhorse — building models, conducting market research and preparing materials that outline strategic options. The role then grows to owning strategic workstreams or acting as a trusted coordinator for a business leader, translating strategy into operational plans. Senior tiers run major strategic reviews and enterprise-wide initiatives close to the CEO, before culminating in evaluating major corporate choices and, at the most senior level, advising boards on strategy and governance.',
    whoSucceeds: [
      'Highly analytical, intellectually curious and politically tactful officers',
      'Officers who have served in Military Operations Directorates, as Military Assistants to General Officers, or in perspective-planning roles are natural fits',
      'Comfort with ambiguity and speaking candidly to senior leadership',
      'Strong financial literacy and presentation skills',
    ],
    whoStruggles: [
      'Weak financial literacy',
      'Difficulty building compelling, structured presentations',
      'A preference for executing standard processes over abstract, unstructured problem-solving',
    ],
    whatYoudNeed: 'An MBA or PGDM in Strategy is often a material differentiator, and can be close to a hard prerequisite for direct entry into top strategy roles; Certified Management Consultant (CMC) is useful if aiming for consulting specifically. A CV must demonstrate the ability to analyse complex data, solve unstructured problems, and operate effectively with senior leadership.',
  ),
  CareerHandbookEntry(
    verticalName: 'Business Development & Strategic Sales',
    whatItDoes: 'This is the revenue engine — long-cycle, high-value, complex business-to-business sales and partnership-building rather than transactional selling. It exists to win major contracts, forge strategic partnerships and open new markets, directly driving the company\'s top-line growth.',
    careerRoadmap: 'The typical path starts with managing the relationship for one or more major clients, understanding their needs and renewing contracts. It grows to actively hunting new business — responding to major proposals, orchestrating pitch teams and negotiating complex pricing — before directing sales strategy for a vertical or region with a team of specialists reporting in. Senior tiers look beyond individual sales to strategic partnerships and new market entry, culminating in ownership of all revenue-generating functions across the enterprise.',
    whoSucceeds: [
      'Charismatic, resilient and highly persistent networkers',
      'Officers who are articulate, comfortable with frequent rejection and have a competitive drive tend to excel',
      'Experience in defence procurement or high-level liaison work translates well',
      'Ability to build rapid rapport with strangers',
    ],
    whoStruggles: [
      'Viewing \'sales\' as a dirty word',
      'Discomfort with compensation tied to performance outcomes',
      'Difficulty building rapport quickly with unfamiliar stakeholders',
    ],
    whatYoudNeed: 'Any graduate degree works, though an MBA is often preferred. Certified Sales Professional and Strategic Account Management (SAMA) certifications help bridge the gap. A CV should prove the ability to influence outcomes, manage complex multi-stakeholder relationships, and drive initiatives with quantifiable value.',
  ),
  CareerHandbookEntry(
    verticalName: 'HR, Talent Management & L&D',
    whatItDoes: 'Human Resources today is a strategic function focused on organisational capability, not just payroll and leave — it acquires, trains, evaluates and retains the people a business needs to run. Learning & Development builds the skills the workforce will need next, while talent management identifies and grooms future leaders.',
    careerRoadmap: 'Officers typically start as the HR partner to a specific business leader, handling grievances, appraisals, hiring and coaching managers. The role grows to managing more complex talent interventions, designing training curricula and handling workforce restructuring and succession planning, before owning HR or talent strategy for a major division and aligning it with business goals. At the senior tiers, the role shapes enterprise-wide culture and organisational design, culminating in advising the CEO on the organisation\'s overall people agenda.',
    whoSucceeds: [
      'Empathetic, process-oriented and emotionally intelligent leaders',
      'Officers with deep experience in training establishments or Adjutant Branch roles tend to fit well',
      'Comfort coaching rather than dictating, and handling emotional workplace conflict',
      'Patience for grievance and compliance processes',
    ],
    whoStruggles: [
      'A preference for issuing orders over coaching',
      'Difficulty handling emotional workplace conflict',
      'Impatience with corporate compliance and grievance processes',
    ],
    whatYoudNeed: 'An HR-focused MBA is often preferred though not always mandatory. SHRM-CP and CIPD are globally recognised certifications that demonstrate familiarity with commercial HR frameworks and labour law. A CV should translate military leadership into HR terms — the scale of personnel managed, training architectures built, and experience with disciplinary or welfare systems.',
  ),
  CareerHandbookEntry(
    verticalName: 'Corporate Affairs, ESG & Public Policy',
    whatItDoes: 'This vertical manages a company\'s relationship with the outside world — governments, regulators, media and communities — and its environmental, social and governance commitments. It exists because external relationships and regulatory posture can materially affect a company\'s licence to operate, reputation and growth; it functions essentially as corporate diplomacy.',
    careerRoadmap: 'The typical path starts with handling ground-level relationships — local CSR projects, monitoring legislative change, drafting regional press materials. It grows to managing strategic stakeholder maps, policy submissions and PR crisis response, then to advocating at state or national level and building alliances with industry bodies. At the senior tiers, the role protects the enterprise\'s global licence to operate and, ultimately, becomes the public face of the company on regulatory and reputational matters alongside the CEO.',
    whoSucceeds: [
      'Articulate, politically savvy and highly networked diplomats',
      'Officers with experience in civil-military liaison, defence attache roles, or extended staff postings in New Delhi tend to excel',
      'JAG officers can also transition well here, since legal training bridges naturally into regulatory interpretation and policy drafting',
      'Comfort navigating bureaucracy and building consensus among diverse stakeholders',
    ],
    whoStruggles: [
      'Being blunt to a fault',
      'Dislike of networking',
      'Difficulty grasping the nuance of public perception and political manoeuvring',
    ],
    whatYoudNeed: 'Any graduate degree works, though communications, law or public policy backgrounds are advantageous. GRI Certified Sustainability Professional or Certificate in ESG (CFA Institute) are increasingly relevant given the growth of ESG requirements. A CV should showcase the ability to navigate complex bureaucracies, build consensus, and communicate under pressure.',
  ),
  CareerHandbookEntry(
    verticalName: 'Defence PSUs, Offsets & GovTech',
    whatItDoes: 'This niche vertical sits within defence contractors or tech firms that sell to government, bridging commercial business with the government and defence procurement apparatus. It helps a company win tenders, meet defence offset obligations, and navigate the bureaucratic processes of government and defence procurement agencies.',
    careerRoadmap: 'Officers typically start by supporting government liaison, tender documentation and stakeholder coordination. The role grows to managing important government relationships, bids and offset-related workstreams, then to owning major PSU or defence-business accounts and shaping procurement requirements in dialogue with military planning bodies. At the senior tiers, the officer leads business strategy across government-facing portfolios and, ultimately, provides board-level or advisory oversight on defence and government-business strategy.',
    whoSucceeds: [
      'Patient, meticulous and well-connected officers who are comfortable with formal process',
      'Officers who have served in procurement, acquisition or weapons and equipment directorates are a strong fit, as are JAG officers given their grounding in government contract and offset compliance',
      'Ability to communicate across both corporate and government/defence-procurement cultures',
      'Comfort with slower, process-heavy decision cycles',
    ],
    whoStruggles: [
      'Little patience for government bureaucracy',
      'Limited understanding of defence acquisition procedure',
      'Wanting a fast-paced, startup-like environment',
    ],
    whatYoudNeed: 'A strong military background is the primary qualification here. Certificate in Public Procurement and Defence Offset Management certification are the listed bridges. A CV should highlight direct experience with government tendering, capital acquisitions, and the technical specifications of defence technology; specific tender or statutory requirements vary by assignment.',
  ),
  CareerHandbookEntry(
    verticalName: 'Corporate Governance',
    whatItDoes: 'Corporate governance makes sure a company is directed and controlled through clear rules, accountable decisions and accurate records, managing the mechanics of board meetings and statutory compliance. It exists because poor governance can lead to fraud, regulatory action, and loss of investor or stakeholder trust.',
    careerRoadmap: 'The typical path starts with handling the mechanics of compliance — drafting minutes, filing statutory returns, tracking compliance dashboards. It grows to managing the board\'s agenda and ensuring resolutions are legally sound, then to acting as primary advisor to the board on its legal duties and navigating governance requirements during major transactions. At the senior tiers, governance is integrated with broader enterprise risk, culminating in advising the chairman and CEO on the organisation\'s overall governance and accountability posture.',
    whoSucceeds: [
      'Meticulous, legally minded and highly discreet officers',
      'Adjutants, Military Secretaries and officers experienced in handling sensitive personnel or statutory military-law matters tend to fit well, as can JAG officers given their grounding in statutory compliance',
      'Comfort enforcing rules on powerful executives',
      'Patience for detailed records and formal decision processes',
    ],
    whoStruggles: [
      'Disorganisation or discomfort with fine print',
      'Reluctance to tell senior executives their proposed action violates policy',
      'Dislike of formal documentation and process',
    ],
    whatYoudNeed: 'A law degree or commerce background is generally preferred. Company Secretary (ICSI) qualification is a substantial professional route that is often close to a hard prerequisite for the most senior governance roles in India, while a Certified Governance Professional credential can open doors in broader compliance roles. A CV should highlight experience managing statutory compliance, high-level administrative boards and complex regulatory frameworks.',
  ),
  CareerHandbookEntry(
    verticalName: 'IT Infrastructure & Cybersecurity',
    whatItDoes: 'This vertical keeps a company\'s digital systems running and keeps attackers out. Infrastructure manages the servers, cloud environments and networks the business depends on; cybersecurity defends that architecture against breaches, ransomware and espionage. It matters because digital downtime or data loss is now an existential risk for most businesses.',
    careerRoadmap: 'Officers typically start running the tactical technology floor — helpdesk, network uptime, patching, basic access controls, or monitoring firewall logs and low-level alerts. The role grows to managing more complex architectures, disaster-recovery planning and cloud migration, then to leading infrastructure or security strategy for a division, including incident-response planning and budget ownership. At the senior tiers, the officer sets enterprise-wide technology posture, culminating in board-level accountability for the organisation\'s overall digital risk.',
    whoSucceeds: [
      'Highly technical, continuously learning officers with a healthy suspicion of vulnerabilities',
      'Corps of Signals, Navy IT and Air Force technical officers are direct fits',
      'Ability to translate deep technical risk into business language for non-technical leaders',
      'Genuine, up-to-date technical aptitude rather than administrative familiarity alone',
    ],
    whoStruggles: [
      'Outdated technical knowledge',
      'Difficulty managing civilian technical talent',
      'Trouble communicating technical concepts to non-technical leaders',
    ],
    whatYoudNeed: 'An engineering or IT degree is close to a prerequisite, particularly for senior technical roles. CISSP and CISM are the gold-standard bridge certifications for security leadership, while ITIL is important for IT operations management. A CV should list the specific technologies, network scale and security frameworks successfully deployed or defended.',
  ),
  CareerHandbookEntry(
    verticalName: 'Tech Product & Data Operations',
    whatItDoes: 'This vertical builds and refines the digital tools a company uses or sells. Product management decides what software to build based on customer needs, while data operations ensures the data a business generates is clean, accessible and analysed to drive decisions. It exists to create competitive advantage through better digital products and data-driven insight.',
    careerRoadmap: 'Officers typically start as the bridge between business teams and engineers — writing requirements, managing delivery cycles and ensuring code ships on time. The role grows to owning a specific feature set or data pipeline, prioritising the engineering backlog, before scaling to owning the roadmap for a major product suite and leading teams of data scientists and product managers. At the senior tiers, the role aligns product vision with corporate strategy, culminating in ownership of the enterprise\'s overall digital product strategy.',
    whoSucceeds: [
      'Analytical, user-empathetic and highly adaptable problem solvers',
      'Officers with experience in technical project management, operations research, or developing bespoke military software tend to excel',
      'Genuine technical fluency rather than only administrative oversight',
      'Comfort with matrixed authority, since engineers typically don\'t report directly to product managers',
    ],
    whoStruggles: [
      'Being technologically averse',
      'Discomfort with matrixed authority and indirect influence',
      'Difficulty making decisions based on ambiguous data',
    ],
    whatYoudNeed: 'A technical degree is generally preferred. Certified Scrum Product Owner and the Google Data Analytics Certificate are the listed bridge certifications, useful for demonstrating familiarity with modern tech development frameworks. A CV should show the ability to solve operational problems using data and technology, highlighting the scale of systems improved.',
  ),
  CareerHandbookEntry(
    verticalName: 'Manufacturing & Technical Systems',
    whatItDoes: 'This vertical manages the physical production of goods, from automobiles to pharmaceuticals. It exists to maximise factory output, minimise defects through quality control, and keep the workforce safe, driven by the relentless pursuit of engineering and process efficiency.',
    careerRoadmap: 'The typical path starts with running a specific shop floor or assembly line, meeting production quotas and managing downtime. It grows to overseeing an entire facility or multiple production lines, implementing lean-manufacturing principles and larger capital projects, before directing manufacturing strategy for a region, balancing production loads across plants and negotiating with labour at a strategic level. At the senior tiers, the role designs the industrial footprint and drives automation adoption, culminating in ownership of the enterprise\'s overall technical and manufacturing capability.',
    whoSucceeds: [
      'Pragmatic, mechanically minded and resilient leaders',
      'EME, Engineers (Sappers), Navy Engineering and Air Force technical officers are natural fits',
      'Comfort with the physical realities of heavy industry — dirt, noise and shop-floor conditions',
      'An underlying engineering background',
    ],
    whoStruggles: [
      'Wanting a purely polished office environment',
      'Lacking an engineering background',
      'Difficulty managing blue-collar labour dynamics',
    ],
    whatYoudNeed: 'A mechanical, electrical or industrial engineering degree is generally expected, particularly in technical manufacturing roles. Six Sigma Black Belt and Certified Quality Engineer (ASQ) are the respected bridge certifications for commercial quality frameworks. A CV should quantify production volumes managed, equipment readiness rates and specific technical projects executed.',
  ),
  CareerHandbookEntry(
    verticalName: 'Aerospace, Drone & Defence Tech',
    whatItDoes: 'This vertical develops and operates aerospace platforms, particularly UAVs and defence or space technology, either commercialising military-grade capability for civilian use or building next-generation hardware for national-security clients. Success depends on integrating engineering, safety and operational disciplines that are all tightly regulated.',
    careerRoadmap: 'Officers typically start by managing tactical deployments — pilot teams, airspace compliance, hardware readiness for a specific fleet. The role grows to managing multi-site technical operations, coordinating with R&D on new platforms and regulatory compliance, before leading operational strategy for a technology division, including client-facing technical requirements. At the senior tiers, the role manages the full lifecycle of a platform and secures major contracts, culminating in P&L ownership for an entire aerospace or defence business unit.',
    whoSucceeds: [
      'Innovative, technically deep and operationally rigorous officers',
      'Army Aviation, Air Force pilots/technical officers and Navy Aviation personnel are strong fits',
      'Ability to bridge fast-moving tech-startup culture with strict aerospace safety standards',
      'Genuine engineering or aviation technical background rather than administrative exposure alone',
    ],
    whoStruggles: [
      'Difficulty adapting to the fast-paced, less structured environment of tech-driven organisations',
      'An aerospace background that is purely administrative rather than technical',
      'Reluctance to build deep technical literacy',
    ],
    whatYoudNeed: 'An engineering or aviation background is close to a requirement. A DGCA Remote Pilot Certificate is important for drone-focused roles, and Systems Engineering certification (INCOSE) helps for broader defence-tech programme work. A CV should highlight direct experience with aerospace platforms, aviation regulation, and leading complex technical operations; specific regulatory approvals should not be assumed from military experience alone.',
  ),
  CareerHandbookEntry(
    verticalName: 'Clinical Practice & Hospital Administration',
    whatItDoes: 'This is the core of commercial healthcare — balancing high-quality patient care with the financial realities of running a hospital. It exists to treat patients well while maintaining occupancy, controlling medical supply costs, and meeting clinical governance and quality-accreditation standards that limit malpractice exposure.',
    careerRoadmap: 'Officers typically start providing direct clinical care and managing a defined medical team or service. The role grows to handling more complex clinical cases while beginning to oversee junior doctors and departmental audits, then to bridging clinical practice and hospital management — coordinating staffing, quality audits and patient-flow issues. At the senior tiers, the role owns hospital-wide clinical quality and resources, culminating in P&L and strategic accountability for the entire institution.',
    whoSucceeds: [
      'Clinically sharp, deeply empathetic doctors who are also commercially aware',
      'AMC officers with experience running field hospitals or command hospitals fit particularly well',
      'Ability to balance clinical ethics with the financial realities of running a hospital',
      'Comfort managing multidisciplinary clinical and administrative teams',
    ],
    whoStruggles: [
      'Distaste for administrative work',
      'Difficulty managing civilian doctors\' professional dynamics',
      'Disregard for the financial cost of medical decisions',
    ],
    whatYoudNeed: 'A recognised medical degree and applicable registration to practise are hard prerequisites for clinical roles, with an MD or MS generally preferred for senior positions. Fellowship in Hospital Administration and an NABH-aligned healthcare quality certification are the listed bridges from military to corporate healthcare management. A CV should highlight clinical competence, the scale of medical facilities managed, and experience with quality accreditation.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Occupational & Industrial Health',
    whatItDoes: 'Situated within heavy industry — manufacturing, mining, oil and gas — this vertical keeps a workforce medically fit for dangerous jobs. It exists to prevent industrial accidents, manage workplace hazards such as chemical exposure and ergonomics, and provide on-site trauma care, reducing corporate liability and lost work-hours.',
    careerRoadmap: 'Officers typically start running an on-site clinic — pre-employment medicals, minor injury treatment, daily health surveillance for hazard-exposed workers. The role grows to managing clinics across multiple plants and analysing injury data to spot systemic safety flaws, then to leading occupational-health strategy for a major industrial division, including compliance and clinic-readiness audits. At the senior tiers, the role integrates occupational health with broader corporate health, safety and environment strategy, culminating in setting policy for a large industrial workforce.',
    whoSucceeds: [
      'Pragmatic, tough, prevention-focused doctors',
      'AMC officers who have served in forward areas dealing with environmental medicine and trauma tend to excel',
      'A preference for hardhat, industrial environments over pristine clinical settings',
      'Comfort working alongside engineering and safety teams',
    ],
    whoStruggles: [
      'Wanting to practise complex specialist medicine',
      'Dislike of factory or industrial environments',
      'Difficulty collaborating with engineering and safety teams',
    ],
    whatYoudNeed: 'A medical degree and applicable medical registration are hard prerequisites. Diploma in Industrial Health (DIH) is the listed bridge certification and directly supports credibility as an industrial-health physician. A CV should show clinical practice, occupational-risk assessment, workplace health programmes and management of medical teams.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Corporate & Employee Health',
    whatItDoes: 'Unlike industrial health, this vertical focuses on the modern, often desk-bound corporate workforce. It exists to reduce absenteeism, manage burnout and mental-health concerns, and help control a company\'s healthcare and insurance spend by keeping employees healthier through screening and wellness programmes.',
    careerRoadmap: 'Officers typically start running a corporate clinic — acute care, executive health checks, basic wellness activities. The role grows to managing health across multiple corporate campuses and analysing aggregated health data to design targeted interventions, then shifts from clinical practice toward programme management — negotiating health packages, designing mental-health support architecture, and managing a wellness budget. At the senior tiers, the role leads enterprise wellness strategy, culminating in advising the executive board on workforce health and business continuity through health crises.',
    whoSucceeds: [
      'Articulate, preventative-focused, tech-savvy doctors',
      'Medical officers experienced in peacetime medical administration and lifestyle-disease management fit well',
      'Comfort designing and presenting wellness programmes to corporate stakeholders',
      'Interest in population-level rather than purely individual patient care',
    ],
    whoStruggles: [
      'Craving the adrenaline of emergency medicine',
      'Dislike of presentation-heavy, programme-management work',
      'Difficulty interacting with demanding corporate executives',
    ],
    whatYoudNeed: 'A medical degree and applicable registration are hard prerequisites. Diploma in Industrial Health (DIH) and Certificate in Occupational Medicine are the listed bridges, useful alongside broader public-health or healthcare-management exposure. A CV should highlight the ability to design and run large-scale preventative health programmes and manage medical administration for large populations.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Pharmaceutical & Life Sciences Medicine',
    whatItDoes: 'This vertical provides the medical and scientific backbone of a pharmaceutical or life-sciences company, ensuring drugs are safe, that clinical trials testing them are scientifically sound, and that marketing claims are accurate. It bridges commercial drug sales with rigorous medical science and regulatory expectations.',
    careerRoadmap: 'Officers typically start providing scientific support to a drug\'s marketing and medical-information functions, training teams and reviewing materials for accuracy. The role grows to managing clinical trials and efficacy data, then to leading medical-affairs or drug-safety work for a therapeutic area, including engagement with external medical experts. At the senior tiers, the role directs medical strategy for a major portfolio, culminating in ultimate medical accountability for a region, including regulator engagement.',
    whoSucceeds: [
      'Highly academic, research-oriented, detail-obsessed doctors',
      'A strong background in research or a specific therapeutic area is generally valued at senior levels',
      'Genuine interest in scientific literature over direct patient interaction',
      'Comfort synthesising complex medical data for non-medical audiences',
    ],
    whoStruggles: [
      'Needing the emotional reward of treating patients directly',
      'Dislike of dense clinical data review',
      'Difficulty navigating corporate bureaucracy',
    ],
    whatYoudNeed: 'A medical degree and applicable registration are hard prerequisites for physician-track roles, generally with research or relevant specialty experience for senior positions. PG Diploma in Clinical Research is the listed bridge certification. A CV should highlight clinical research conducted, publications, and the ability to translate complex medical data for non-medical audiences.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Health Insurance & Managed Care',
    whatItDoes: 'This vertical operates inside insurance companies to evaluate medical risk and control costs, checking whether hospital treatments being claimed are medically necessary and appropriately priced. It exists to prevent over-billing and unnecessary treatment while ensuring legitimate claims are paid fairly.',
    careerRoadmap: 'Officers typically start by reviewing medical claims and hospital bills against clinical criteria. The role grows to handling escalations and high-value claims, auditing network hospitals and negotiating standard tariffs, then to analysing population health data to inform policy pricing and coverage rules. At the senior tiers, the role directs claims and underwriting strategy for the company, culminating in setting the insurer\'s overall clinical and medical-risk direction.',
    whoSucceeds: [
      'Analytical, financially minded, objective doctors',
      'Officers with experience in ECHS management or medical board processing are highly suited, since they already understand utilisation review',
      'Comfort making consistent decisions from records and policy rules',
      'Ability to balance patient care considerations with cost control',
    ],
    whoStruggles: [
      'Feeling insurance work is inherently at odds with patient care',
      'Discomfort denying claims',
      'Wanting to practise clinical medicine directly',
    ],
    whatYoudNeed: 'A medical qualification and applicable registration are hard prerequisites for physician-track roles. Diploma in Healthcare Management is the listed bridge that helps with management credibility. A CV should highlight experience with medical administration, cost containment, and auditing medical records.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Digital Health / HealthTech',
    whatItDoes: 'This vertical sits inside tech companies building medical software — from telemedicine platforms to diagnostic tools — ensuring the software is clinically safe, genuinely useful to doctors, and compliant with medical data privacy requirements. It bridges the gap between software engineers and clinical reality.',
    careerRoadmap: 'Officers typically start as the clinical subject-matter expert supporting developers, defining what data and workflows a clinical product actually needs. The role grows to validating the clinical accuracy of a product and contributing to trials or model training, then to owning the roadmap for a piece of medical software, including its integration into hospital systems. At the senior tiers, the role leads medical strategy across a portfolio of digital products, culminating in serving as the clinical voice of the company to hospital and enterprise customers.',
    whoSucceeds: [
      'Tech-curious, innovative, adaptable doctors',
      'Medical officers who have implemented digital health-record or clinical IT systems, or who naturally gravitate toward technology, fit well',
      'Comfort communicating with non-medical software engineers',
      'Willingness to operate in a less structured, faster-moving environment',
    ],
    whoStruggles: [
      'Discomfort with technology',
      'Expecting a highly structured corporate environment, since digital health teams can be fast-moving and less formal',
      'Difficulty communicating with non-medical technical colleagues',
    ],
    whatYoudNeed: 'Medical qualification and registration are required for physician-track positions. Certificate in Digital Health / Health Informatics is the listed bridge. A CV should demonstrate genuine interest in technology and process improvement, along with any experience implementing or improving digital systems in military healthcare.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Public Health, Research & Medical Education',
    whatItDoes: 'This vertical focuses on population-level health rather than individual patients — disease prevention, epidemiological research, surveillance, and medical education. It exists to turn evidence into effective health interventions and to improve outcomes across communities rather than one patient at a time.',
    careerRoadmap: 'Officers typically start executing health programmes on the ground — surveillance, field activity, education. The role grows to leading research or public-health workstreams and interpreting evidence, then to running larger epidemiology or research teams and shaping major interventions. At the senior tiers, the role directs national-level health programmes and partnerships, culminating in setting research or public-health strategy across an institution or system.',
    whoSucceeds: [
      'Mission-driven, data-oriented, politically astute doctors',
      'Officers with deep experience in military hygiene, preventive-medicine practice, or large-scale cantonment health campaigns tend to excel',
      'Enjoyment of evidence, teaching and large-system problems over individual patient care',
      'Comfort working with civil administration and slower institutional timelines',
    ],
    whoStruggles: [
      'Wanting corporate-level pace and rewards',
      'Dislike of grant writing and administrative process',
      'Frustration with the slower pace of government and institutional bureaucracy',
    ],
    whatYoudNeed: 'A medical qualification and applicable registration are required for physician-track roles. Master of Public Health (MPH) is the listed bridge and can be valuable even for experienced clinicians. A CV should highlight population-level health campaigns run, epidemiological data managed, and experience working with civil administration.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Specialized Environment Medicine',
    whatItDoes: 'This niche vertical provides medical care in extreme or isolated commercial environments — commercial aviation, offshore or remote industrial sites, high-altitude operations. It exists to manage the unique physiological stresses of these environments and to handle emergencies where immediate hospital access is not possible.',
    careerRoadmap: 'Officers typically start as the sole or lead clinician at a remote site, handling immediate trauma and making high-stakes evacuation calls. The role grows to managing medical protocols across multiple remote sites, training paramedics and auditing clinic readiness, then to setting medical strategy for an entire hazardous division, including supply chains and compliance with international health regulations. At the senior tiers, the role oversees health strategy for an entire specialised fleet or operation, advising leadership on the human limits of extreme operations.',
    whoSucceeds: [
      'Highly independent doctors who stay calm under extreme pressure with broad clinical range',
      'Aviation-medicine specialists and officers with extensive high-altitude or field-area experience are strong fits',
      'Comfort operating without advanced diagnostics or immediate backup',
      'Tolerance for isolation and demanding physical environments',
    ],
    whoStruggles: [
      'Heavy reliance on advanced diagnostics to practise medicine',
      'Difficulty with isolation',
      'Motion sickness or claustrophobia in confined operating environments',
    ],
    whatYoudNeed: 'A medical qualification and registration are hard prerequisites. Diploma in Aviation Medicine (DAvMed) is the listed bridge certification where aviation medicine is relevant. A CV should demonstrate the ability to operate autonomously in high-stakes situations with limited immediate backup, and prior operational or environmental medical leadership.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Government / PSU / Institutional Healthcare',
    whatItDoes: 'Public Sector Undertakings and large government institutions maintain their own extensive healthcare systems. This vertical provides comprehensive healthcare to employees and dependents, combining clinical care with staffing, facilities, procurement and service administration within an institutional structure.',
    careerRoadmap: 'Officers typically start providing clinical care within an institutional hospital or dispensary. The role grows to taking on administrative duties — managing a department, organising health camps, overseeing medical supply procurement — then to running a complete hospital or medical unit for a specific institution or plant, including budget and local stakeholder management. At the senior tiers, the role coordinates medical services across multiple institutions or a region, culminating in directing medical services at the system level.',
    whoSucceeds: [
      'Administratively strong, patient, bureaucratically savvy doctors',
      'This is close to the civilian equivalent of the Armed Forces Medical Services, and officers who thrive in structured, hierarchical medical systems tend to find it a seamless transition',
      'Comfort with government procurement and institutional processes',
      'Willingness to manage large dependent populations',
    ],
    whoStruggles: [
      'Leaving the military specifically to escape bureaucracy',
      'Wanting a fast-paced corporate environment',
      'Desiring highly variable, performance-based pay',
    ],
    whatYoudNeed: 'A medical degree and applicable registration are hard prerequisites. Diploma in Hospital Administration is the listed bridge certification and is highly valued. A CV should mirror military medical administrative experience — command of medical units, management of dependent healthcare, and familiarity with government procurement rules.',
    restrictionNote: 'This path is realistic mainly for officers from the Army Medical Corps or Navy/Air Force medical branches.',
  ),
  CareerHandbookEntry(
    verticalName: 'Corporate Legal & In-House Counsel',
    whatItDoes: 'In-house counsel is the legal nervous system of a company, drafting and reviewing contracts, ensuring the business operates within the law, and advising leadership on the legal risk of business decisions. It exists to enable business growth while preventing serious legal liability.',
    careerRoadmap: 'Officers typically start with the daily work of contract review — drafting standard agreements and answering routine legal queries from business teams. The role grows to managing complex, high-value transactions and negotiating directly with counterparties\' legal teams, then to leading a team of lawyers for a business unit, structuring legal frameworks for new launches and managing external counsel. At the senior tiers, the role operates at enterprise level on major litigation and international expansion, culminating in serving as the company\'s ultimate legal authority advising the board.',
    whoSucceeds: [
      'Detail-obsessed, commercially pragmatic and highly articulate lawyers',
      'JAG officers who have handled complex procurement contracts, Ministry of Defence legal advising, or statutory drafting tend to transition well',
      'Ability to find lawful paths to business objectives rather than simply saying no',
      'Comfort with calculated commercial risk-taking',
    ],
    whoStruggles: [
      'Wanting to litigate in court every day',
      'Weak grasp of basic business finance',
      'Discomfort taking calculated legal risks',
    ],
    whatYoudNeed: 'A recognised law degree and the right to practise where required are hard prerequisites for counsel roles. PG Diploma in Corporate Law is the listed bridge, useful for moving from military or criminal law into commercial practice — it is a bridge, not a substitute for the law qualification itself. A CV should highlight contract drafting, statutory interpretation, and experience advising senior leadership on legal-administrative issues.',
    restrictionNote: 'This path is realistic mainly for officers from the Judge Advocate General\'s (JAG) department.',
  ),
  CareerHandbookEntry(
    verticalName: 'Litigation & Dispute Management',
    whatItDoes: 'When contracts fail or a company is sued, this function takes over the company\'s legal battles in courts and tribunals. In-house litigation managers typically hire and manage external counsel rather than arguing cases themselves, strategising the defence and deciding when to settle versus fight.',
    careerRoadmap: 'Officers typically start managing case files — gathering evidence, drafting briefings for external counsel and tracking hearings. The role grows to managing a portfolio of cases across a region, drafting complex pleadings and evaluating external legal strategy, then to setting enterprise litigation strategy, deciding which cases must be fought and which settled. At the senior tiers, the role manages high-stakes, multi-jurisdictional litigation, culminating in ultimate accountability for the company\'s legal-defence strategy and advising the board on legal exposure.',
    whoSucceeds: [
      'Combative, strategic and deeply analytical lawyers',
      'JAG officers with extensive Court Martial experience, particularly in prosecuting or defending complex cases, tend to be strong fits',
      'Comfort managing the unpredictability of the judicial process',
      'Ability to manage external counsel effectively',
    ],
    whoStruggles: [
      'A preference for drafting contracts quietly rather than managing disputes',
      'Dislike of the unpredictable nature of litigation',
      'Difficulty managing external consultants and lawyers',
    ],
    whatYoudNeed: 'A law degree and Bar enrolment are prerequisites. LLM (Dispute Resolution) is the listed bridge certification. A CV should quantify the scale of cases handled, outcomes achieved, and the ability to manage complex evidentiary trials and appeals.',
    restrictionNote: 'This path is realistic mainly for officers from the Judge Advocate General\'s (JAG) department.',
  ),
  CareerHandbookEntry(
    verticalName: 'Arbitration & Alternative Dispute Resolution',
    whatItDoes: 'Because traditional courts can be slow, companies increasingly use arbitration to settle large commercial disputes. This vertical involves acting as arbitration counsel for a company or serving as a neutral arbitrator, resolving complex, high-value disputes privately and relatively quickly.',
    careerRoadmap: 'Officers typically start doing the underlying legal research — case law, statements of claim or defence, organising documentary evidence. The role grows to acting as a neutral party for smaller disputes or as lead counsel managing arbitration strategy, then to being recognised as a domain expert appointed to arbitral tribunals for larger corporate disputes. At the senior tiers, the role leads an organisation\'s or firm\'s approach to resolving disputes outside court, culminating in sitting on panels for major cross-border matters or leading an arbitration institution.',
    whoSucceeds: [
      'Highly intellectual, deeply specialised and objective lawyers',
      'JAG officers with experience adjudicating complex administrative or contractual disputes tend to excel',
      'Extreme patience for reading lengthy commercial contracts and records',
      'Formal legal qualification, since arbitrator appointment is not automatic and depends on the institution',
    ],
    whoStruggles: [
      'Limited patience for reading extensive commercial documentation',
      'A preference for the more adversarial drama of criminal litigation',
      'Wanting direct command authority rather than a neutral, procedural role',
    ],
    whatYoudNeed: 'A law qualification is a hard prerequisite for most professional ADR pathways, and formal appointment as an arbitrator is not automatic. Chartered Institute of Arbitrators (CIArb) certification is the listed bridge and carries real weight internationally. A CV should highlight experience in adjudicatory roles and handling complex contractual disputes.',
    restrictionNote: 'This path is realistic mainly for officers from the Judge Advocate General\'s (JAG) department.',
  ),
  CareerHandbookEntry(
    verticalName: 'Regulatory & Compliance Affairs',
    whatItDoes: 'Every regulated industry has dense rules that a company must translate into operational practice. This vertical ensures the business follows applicable laws, licences and regulator expectations, preventing loss of licence to operate or crippling fines for violations.',
    careerRoadmap: 'Officers typically start running compliance checklists and audits against specific requirements. The role grows to managing the compliance architecture — designing training and handling initial responses to regulatory audits — then to interfacing directly with regulators, analysing the impact of new laws and directing operational change. At the senior tiers, the role builds a global compliance framework across jurisdictions, culminating in independent, board-facing accountability for the organisation\'s compliance posture.',
    whoSucceeds: [
      'Process-oriented, highly ethical and uncompromising lawyers',
      'JAG officers who have managed complex statutory compliance within the military framework tend to be a strong fit',
      'Willingness to challenge powerful stakeholders and document decisions',
      'Comfort with rules and repetitive control testing',
    ],
    whoStruggles: [
      'Finding regulatory text tedious',
      'Reluctance to halt profitable activity for compliance reasons',
      'A preference for creative legal argument over rigid rule adherence',
    ],
    whatYoudNeed: 'A law degree is highly useful and may be required for some legal-regulatory roles, though not every compliance position requires practising status. Certified Compliance Professional is the listed bridge certification. A CV should show the ability to build compliance frameworks, conduct legal audits, and interact with statutory or governmental authorities.',
    restrictionNote: 'This path is realistic mainly for officers from the Judge Advocate General\'s (JAG) department.',
  ),
  CareerHandbookEntry(
    verticalName: 'Labour & Employee Relations Law',
    whatItDoes: 'This is the legal side of HR — managing the legal complexities of hiring, firing, union negotiation and workplace harassment. It exists to protect a company from labour disputes and wrongful-termination exposure while keeping the workplace lawful and industrially stable.',
    careerRoadmap: 'Officers typically start handling tactical legal issues — disciplinary notices, labour-law compliance, harassment-inquiry processes. The role grows to managing complex industrial relations, including layoffs and union wage negotiations, then to setting labour strategy for a region, including the legal risk of major workforce restructuring. At the senior tiers, the role bridges legal and HR at the executive level, culminating in leading the organisation\'s employee-relations agenda from a legal and compliance-driven perspective.',
    whoSucceeds: [
      'Tough, empathetic and highly articulate negotiators',
      'JAG officers who have handled complex disciplinary proceedings, Courts of Inquiry into personnel matters, or welfare law tend to excel',
      'Comfort with confrontation and negotiation',
      'Genuine interest in the human element behind legal disputes',
    ],
    whoStruggles: [
      'Avoiding confrontation',
      'Difficulty understanding blue-collar union dynamics',
      'Limited empathy for the human element of legal disputes',
    ],
    whatYoudNeed: 'A law degree is required, along with applicable legal standing for legal-track positions. PG Diploma in Labour Law is the listed bridge certification, useful for demonstrating knowledge of civilian industrial-dispute practice. A CV should highlight experience in disciplinary management, conducting formal inquiries, and managing complex personnel-legal issues.',
    restrictionNote: 'This path is realistic mainly for officers from the Judge Advocate General\'s (JAG) department.',
  ),
];
